import type { GrammarExercise } from "../types/index.js";

// ─── Verb Conjugation (22 exercises, Klasse 1–3) ─────────────────────────────

export const verbConjugationExercises: GrammarExercise[] = [
  // spielen
  { id: "vc-spielen-ich", category: "verb-conjugation", klasse: 2,
    prompt: "Ich ___ Fußball. (spielen)",
    options: ["spiele", "spielst", "spielt", "spielen"],
    correctAnswer: "spiele",
    explanation: "Bei 'ich' hängt man -e an: spiel-e", xpReward: 5 },
  { id: "vc-spielen-du", category: "verb-conjugation", klasse: 1,
    prompt: "Du ___ gern Fußball. (spielen)",
    options: ["spiele", "spielst", "spielt", "spielen"],
    correctAnswer: "spielst",
    explanation: "Bei 'du' hängt man -st an: spiel-st", xpReward: 5 },
  { id: "vc-spielen-er", category: "verb-conjugation", klasse: 2,
    prompt: "Er ___ täglich im Garten. (spielen)",
    options: ["spiele", "spielst", "spielt", "spielen"],
    correctAnswer: "spielt",
    explanation: "Bei 'er/sie/es' hängt man -t an: spiel-t", xpReward: 5 },

  // laufen
  { id: "vc-laufen-ich", category: "verb-conjugation", klasse: 2,
    prompt: "Ich ___ sehr schnell. (laufen)",
    options: ["laufe", "läufst", "läuft", "laufen"],
    correctAnswer: "laufe",
    explanation: "Bei 'ich' bleibt der Stammvokal: lauf-e", xpReward: 5 },
  { id: "vc-laufen-du", category: "verb-conjugation", klasse: 2,
    prompt: "Du ___ jeden Morgen. (laufen)",
    options: ["laufe", "läufst", "läuft", "laufen"],
    correctAnswer: "läufst",
    explanation: "Bei 'du' ändert sich au→äu: läuf-st", xpReward: 5 },

  // essen
  { id: "vc-essen-ich", category: "verb-conjugation", klasse: 2,
    prompt: "Ich ___ gern Pizza. (essen)",
    options: ["esse", "isst", "esst", "essen"],
    correctAnswer: "esse",
    explanation: "Bei 'ich': ess-e", xpReward: 5 },
  { id: "vc-essen-du", category: "verb-conjugation", klasse: 2,
    prompt: "Du ___ dein Brot. (essen)",
    options: ["esse", "isst", "esst", "essen"],
    correctAnswer: "isst",
    explanation: "Bei 'du' ändert sich e→i: iss-t", xpReward: 5 },

  // trinken
  { id: "vc-trinken-ich", category: "verb-conjugation", klasse: 2,
    prompt: "Ich ___ Wasser. (trinken)",
    options: ["trinke", "trinkst", "trinkt", "trinken"],
    correctAnswer: "trinke",
    explanation: "Bei 'ich': trink-e", xpReward: 5 },
  { id: "vc-trinken-wir", category: "verb-conjugation", klasse: 3,
    prompt: "Wir ___ Saft zusammen. (trinken)",
    options: ["trinke", "trinkst", "trinkt", "trinken"],
    correctAnswer: "trinken",
    explanation: "Bei 'wir': trink-en", xpReward: 5 },

  // schreiben
  { id: "vc-schreiben-ich", category: "verb-conjugation", klasse: 2,
    prompt: "Ich ___ einen Brief. (schreiben)",
    options: ["schreibe", "schreibst", "schreibt", "schreiben"],
    correctAnswer: "schreibe",
    explanation: "Bei 'ich': schreib-e", xpReward: 5 },
  { id: "vc-schreiben-du", category: "verb-conjugation", klasse: 2,
    prompt: "Du ___ einen Aufsatz. (schreiben)",
    options: ["schreibe", "schreibst", "schreibt", "schreiben"],
    correctAnswer: "schreibst",
    explanation: "Bei 'du': schreib-st", xpReward: 5 },

  // lesen
  { id: "vc-lesen-du", category: "verb-conjugation", klasse: 2,
    prompt: "Du ___ ein Buch. (lesen)",
    options: ["lese", "liest", "lest", "lesen"],
    correctAnswer: "liest",
    explanation: "Bei 'du' ändert sich e→ie: lies-t", xpReward: 5 },
  { id: "vc-lesen-er", category: "verb-conjugation", klasse: 3,
    prompt: "Er ___ die Zeitung. (lesen)",
    options: ["lese", "liest", "lest", "lesen"],
    correctAnswer: "liest",
    explanation: "Bei 'er/sie/es' ändert sich e→ie: lies-t", xpReward: 5 },

  // machen
  { id: "vc-machen-er", category: "verb-conjugation", klasse: 2,
    prompt: "Er ___ seine Aufgaben. (machen)",
    options: ["mache", "machst", "macht", "machen"],
    correctAnswer: "macht",
    explanation: "Bei 'er/sie/es': mach-t", xpReward: 5 },
  { id: "vc-machen-wir", category: "verb-conjugation", klasse: 3,
    prompt: "Wir ___ einen Ausflug. (machen)",
    options: ["mache", "machst", "macht", "machen"],
    correctAnswer: "machen",
    explanation: "Bei 'wir': mach-en", xpReward: 5 },

  // haben
  { id: "vc-haben-ich", category: "verb-conjugation", klasse: 2,
    prompt: "Ich ___ Hunger. (haben)",
    options: ["habe", "hast", "hat", "haben"],
    correctAnswer: "habe",
    explanation: "Bei 'ich': hab-e", xpReward: 5 },
  { id: "vc-haben-er", category: "verb-conjugation", klasse: 2,
    prompt: "Er ___ einen Hund. (haben)",
    options: ["habe", "hast", "hat", "haben"],
    correctAnswer: "hat",
    explanation: "Bei 'er/sie/es': hat (unregelmäßig)", xpReward: 5 },

  // sein
  { id: "vc-sein-ich", category: "verb-conjugation", klasse: 2,
    prompt: "Ich ___ müde. (sein)",
    options: ["bin", "bist", "ist", "sind"],
    correctAnswer: "bin",
    explanation: "Bei 'ich': bin (sehr unregelmäßig)", xpReward: 5 },
  { id: "vc-sein-du", category: "verb-conjugation", klasse: 3,
    prompt: "Du ___ sehr nett. (sein)",
    options: ["bin", "bist", "ist", "sind"],
    correctAnswer: "bist",
    explanation: "Bei 'du': bist (sehr unregelmäßig)", xpReward: 5 },
  { id: "vc-sein-wir", category: "verb-conjugation", klasse: 3,
    prompt: "Wir ___ gute Freunde. (sein)",
    options: ["bin", "bist", "ist", "sind"],
    correctAnswer: "sind",
    explanation: "Bei 'wir': sind (sehr unregelmäßig)", xpReward: 5 },

  // gehen
  { id: "vc-gehen-ich", category: "verb-conjugation", klasse: 2,
    prompt: "Ich ___ zur Schule. (gehen)",
    options: ["gehe", "gehst", "geht", "gehen"],
    correctAnswer: "gehe",
    explanation: "Bei 'ich': geh-e", xpReward: 5 },
  { id: "vc-gehen-du", category: "verb-conjugation", klasse: 2,
    prompt: "Du ___ nach Hause. (gehen)",
    options: ["gehe", "gehst", "geht", "gehen"],
    correctAnswer: "gehst",
    explanation: "Bei 'du': geh-st", xpReward: 5 },
];

// ─── Noun Gender (31 nouns with emoji, Klasse 1–4) ───────────────────────────

export const nounGenderExercises: GrammarExercise[] = [
  // Klasse 1
  { id: "ng-hund", category: "noun-gender", klasse: 1,
    prompt: "🐕 Hund", options: ["der", "die", "das"], correctAnswer: "der",
    explanation: "Es heißt 'der Hund'", xpReward: 5 },
  { id: "ng-katze", category: "noun-gender", klasse: 1,
    prompt: "🐈 Katze", options: ["der", "die", "das"], correctAnswer: "die",
    explanation: "Es heißt 'die Katze'", xpReward: 5 },
  { id: "ng-haus", category: "noun-gender", klasse: 1,
    prompt: "🏠 Haus", options: ["der", "die", "das"], correctAnswer: "das",
    explanation: "Es heißt 'das Haus'", xpReward: 5 },
  { id: "ng-baum", category: "noun-gender", klasse: 1,
    prompt: "🌳 Baum", options: ["der", "die", "das"], correctAnswer: "der",
    explanation: "Es heißt 'der Baum'", xpReward: 5 },
  { id: "ng-blume", category: "noun-gender", klasse: 1,
    prompt: "🌸 Blume", options: ["der", "die", "das"], correctAnswer: "die",
    explanation: "Es heißt 'die Blume'", xpReward: 5 },
  { id: "ng-kind", category: "noun-gender", klasse: 1,
    prompt: "👶 Kind", options: ["der", "die", "das"], correctAnswer: "das",
    explanation: "Es heißt 'das Kind'", xpReward: 5 },
  { id: "ng-apfel", category: "noun-gender", klasse: 1,
    prompt: "🍎 Apfel", options: ["der", "die", "das"], correctAnswer: "der",
    explanation: "Es heißt 'der Apfel'", xpReward: 5 },
  { id: "ng-sonne", category: "noun-gender", klasse: 1,
    prompt: "☀️ Sonne", options: ["der", "die", "das"], correctAnswer: "die",
    explanation: "Es heißt 'die Sonne'", xpReward: 5 },
  { id: "ng-heft", category: "noun-gender", klasse: 1,
    prompt: "📓 Heft", options: ["der", "die", "das"], correctAnswer: "das",
    explanation: "Es heißt 'das Heft'", xpReward: 5 },
  { id: "ng-ball", category: "noun-gender", klasse: 1,
    prompt: "⚽ Ball", options: ["der", "die", "das"], correctAnswer: "der",
    explanation: "Es heißt 'der Ball'", xpReward: 5 },
  { id: "ng-pferd", category: "noun-gender", klasse: 1,
    prompt: "🐴 Pferd", options: ["der", "die", "das"], correctAnswer: "das",
    explanation: "Es heißt 'das Pferd'", xpReward: 5 },
  { id: "ng-schule", category: "noun-gender", klasse: 1,
    prompt: "🏫 Schule", options: ["der", "die", "das"], correctAnswer: "die",
    explanation: "Es heißt 'die Schule'", xpReward: 5 },
  // Klasse 2
  { id: "ng-tisch", category: "noun-gender", klasse: 2,
    prompt: "🪑 Tisch", options: ["der", "die", "das"], correctAnswer: "der",
    explanation: "Es heißt 'der Tisch'", xpReward: 5 },
  { id: "ng-auto", category: "noun-gender", klasse: 2,
    prompt: "🚗 Auto", options: ["der", "die", "das"], correctAnswer: "das",
    explanation: "Es heißt 'das Auto'", xpReward: 5 },
  { id: "ng-vogel", category: "noun-gender", klasse: 2,
    prompt: "🐦 Vogel", options: ["der", "die", "das"], correctAnswer: "der",
    explanation: "Es heißt 'der Vogel'", xpReward: 5 },
  { id: "ng-fisch", category: "noun-gender", klasse: 2,
    prompt: "🐟 Fisch", options: ["der", "die", "das"], correctAnswer: "der",
    explanation: "Es heißt 'der Fisch'", xpReward: 5 },
  { id: "ng-fenster", category: "noun-gender", klasse: 2,
    prompt: "🪟 Fenster", options: ["der", "die", "das"], correctAnswer: "das",
    explanation: "Es heißt 'das Fenster'", xpReward: 5 },
  { id: "ng-strasse", category: "noun-gender", klasse: 2,
    prompt: "🛣️ Straße", options: ["der", "die", "das"], correctAnswer: "die",
    explanation: "Es heißt 'die Straße'", xpReward: 5 },
  { id: "ng-fahrrad", category: "noun-gender", klasse: 2,
    prompt: "🚲 Fahrrad", options: ["der", "die", "das"], correctAnswer: "das",
    explanation: "Es heißt 'das Fahrrad'", xpReward: 5 },
  { id: "ng-buch", category: "noun-gender", klasse: 2,
    prompt: "📚 Buch", options: ["der", "die", "das"], correctAnswer: "das",
    explanation: "Es heißt 'das Buch'", xpReward: 5 },
  { id: "ng-bleistift", category: "noun-gender", klasse: 2,
    prompt: "✏️ Bleistift", options: ["der", "die", "das"], correctAnswer: "der",
    explanation: "Es heißt 'der Bleistift'", xpReward: 5 },
  { id: "ng-madchen", category: "noun-gender", klasse: 2,
    prompt: "👧 Mädchen", options: ["der", "die", "das"], correctAnswer: "das",
    explanation: "Alle Wörter mit -chen sind 'das': das Mädchen", xpReward: 5 },
  // Klasse 3
  { id: "ng-berg", category: "noun-gender", klasse: 3,
    prompt: "⛰️ Berg", options: ["der", "die", "das"], correctAnswer: "der",
    explanation: "Es heißt 'der Berg'", xpReward: 5 },
  { id: "ng-fluss", category: "noun-gender", klasse: 3,
    prompt: "🌊 Fluss", options: ["der", "die", "das"], correctAnswer: "der",
    explanation: "Es heißt 'der Fluss'", xpReward: 5 },
  { id: "ng-stadt", category: "noun-gender", klasse: 3,
    prompt: "🏙️ Stadt", options: ["der", "die", "das"], correctAnswer: "die",
    explanation: "Es heißt 'die Stadt'", xpReward: 5 },
  { id: "ng-wald", category: "noun-gender", klasse: 3,
    prompt: "🌲 Wald", options: ["der", "die", "das"], correctAnswer: "der",
    explanation: "Es heißt 'der Wald'", xpReward: 5 },
  { id: "ng-meer", category: "noun-gender", klasse: 3,
    prompt: "🌊 Meer", options: ["der", "die", "das"], correctAnswer: "das",
    explanation: "Es heißt 'das Meer'", xpReward: 5 },
  { id: "ng-brot", category: "noun-gender", klasse: 3,
    prompt: "🍞 Brot", options: ["der", "die", "das"], correctAnswer: "das",
    explanation: "Es heißt 'das Brot'", xpReward: 5 },
  // Klasse 4
  { id: "ng-zeitung", category: "noun-gender", klasse: 4,
    prompt: "📰 Zeitung", options: ["der", "die", "das"], correctAnswer: "die",
    explanation: "Es heißt 'die Zeitung'", xpReward: 5 },
  { id: "ng-telefon", category: "noun-gender", klasse: 4,
    prompt: "📱 Telefon", options: ["der", "die", "das"], correctAnswer: "das",
    explanation: "Es heißt 'das Telefon'", xpReward: 5 },
  { id: "ng-computer", category: "noun-gender", klasse: 4,
    prompt: "💻 Computer", options: ["der", "die", "das"], correctAnswer: "der",
    explanation: "Es heißt 'der Computer'", xpReward: 5 },
];

// ─── Singular & Plural (22 exercises, Klasse 1–4) ────────────────────────────

export const pluralExercises: GrammarExercise[] = [
  // Klasse 1
  { id: "pl-hund", category: "plural", klasse: 1,
    prompt: "Was ist die Mehrzahl von 'Hund'?",
    options: ["Hunde", "Hünde", "Hunden", "Hunds"],
    correctAnswer: "Hunde",
    explanation: "Die Mehrzahl von Hund ist Hunde", xpReward: 5 },
  { id: "pl-katze", category: "plural", klasse: 1,
    prompt: "Was ist die Mehrzahl von 'Katze'?",
    options: ["Katzen", "Kätze", "Katzens", "Katzes"],
    correctAnswer: "Katzen",
    explanation: "Die Mehrzahl von Katze ist Katzen", xpReward: 5 },
  { id: "pl-baum", category: "plural", klasse: 2,
    prompt: "Was ist die Mehrzahl von 'Baum'?",
    options: ["Bäume", "Baums", "Baume", "Bäum"],
    correctAnswer: "Bäume",
    explanation: "Die Mehrzahl von Baum ist Bäume (Umlaut + e)", xpReward: 5 },
  { id: "pl-haus", category: "plural", klasse: 2,
    prompt: "Was ist die Mehrzahl von 'Haus'?",
    options: ["Häuser", "Haus", "Häuse", "Hauser"],
    correctAnswer: "Häuser",
    explanation: "Die Mehrzahl von Haus ist Häuser (Umlaut + er)", xpReward: 5 },
  { id: "pl-kind", category: "plural", klasse: 1,
    prompt: "Was ist die Mehrzahl von 'Kind'?",
    options: ["Kinder", "Kinde", "Kindern", "Kinds"],
    correctAnswer: "Kinder",
    explanation: "Die Mehrzahl von Kind ist Kinder", xpReward: 5 },
  { id: "pl-blume", category: "plural", klasse: 1,
    prompt: "Was ist die Mehrzahl von 'Blume'?",
    options: ["Blumen", "Blümen", "Blumes", "Blume"],
    correctAnswer: "Blumen",
    explanation: "Die Mehrzahl von Blume ist Blumen", xpReward: 5 },
  // Klasse 2
  { id: "pl-buch", category: "plural", klasse: 2,
    prompt: "Was ist die Mehrzahl von 'Buch'?",
    options: ["Bücher", "Buchs", "Buchen", "Büch"],
    correctAnswer: "Bücher",
    explanation: "Die Mehrzahl von Buch ist Bücher (Umlaut + er)", xpReward: 5 },
  { id: "pl-tisch", category: "plural", klasse: 2,
    prompt: "Was ist die Mehrzahl von 'Tisch'?",
    options: ["Tische", "Tischen", "Tischs", "Täsche"],
    correctAnswer: "Tische",
    explanation: "Die Mehrzahl von Tisch ist Tische", xpReward: 5 },
  { id: "pl-ball", category: "plural", klasse: 2,
    prompt: "Was ist die Mehrzahl von 'Ball'?",
    options: ["Bälle", "Balls", "Balle", "Bällen"],
    correctAnswer: "Bälle",
    explanation: "Die Mehrzahl von Ball ist Bälle (Umlaut + e)", xpReward: 5 },
  { id: "pl-auto", category: "plural", klasse: 2,
    prompt: "Was ist die Mehrzahl von 'Auto'?",
    options: ["Autos", "Autoen", "Aute", "Äutos"],
    correctAnswer: "Autos",
    explanation: "Die Mehrzahl von Auto ist Autos (Fremdwort: + s)", xpReward: 5 },
  { id: "pl-vogel", category: "plural", klasse: 2,
    prompt: "Was ist die Mehrzahl von 'Vogel'?",
    options: ["Vögel", "Vogels", "Vogeln", "Vogele"],
    correctAnswer: "Vögel",
    explanation: "Die Mehrzahl von Vogel ist Vögel (Umlaut)", xpReward: 5 },
  { id: "pl-apfel", category: "plural", klasse: 2,
    prompt: "Was ist die Mehrzahl von 'Apfel'?",
    options: ["Äpfel", "Äpfels", "Apfeln", "Apfele"],
    correctAnswer: "Äpfel",
    explanation: "Die Mehrzahl von Apfel ist Äpfel (Umlaut)", xpReward: 5 },
  { id: "pl-stuhl", category: "plural", klasse: 2,
    prompt: "Was ist die Mehrzahl von 'Stuhl'?",
    options: ["Stühle", "Stuhls", "Stuhlen", "Stühlen"],
    correctAnswer: "Stühle",
    explanation: "Die Mehrzahl von Stuhl ist Stühle (Umlaut + e)", xpReward: 5 },
  { id: "pl-heft", category: "plural", klasse: 2,
    prompt: "Was ist die Mehrzahl von 'Heft'?",
    options: ["Hefte", "Heften", "Heftse", "Heft"],
    correctAnswer: "Hefte",
    explanation: "Die Mehrzahl von Heft ist Hefte", xpReward: 5 },
  // Klasse 3
  { id: "pl-berg", category: "plural", klasse: 3,
    prompt: "Was ist die Mehrzahl von 'Berg'?",
    options: ["Berge", "Bärge", "Bergs", "Bergen"],
    correctAnswer: "Berge",
    explanation: "Die Mehrzahl von Berg ist Berge", xpReward: 5 },
  { id: "pl-freund", category: "plural", klasse: 3,
    prompt: "Was ist die Mehrzahl von 'Freund'?",
    options: ["Freunde", "Freunden", "Freunds", "Freunde"],
    correctAnswer: "Freunde",
    explanation: "Die Mehrzahl von Freund ist Freunde", xpReward: 5 },
  { id: "pl-stadt", category: "plural", klasse: 3,
    prompt: "Was ist die Mehrzahl von 'Stadt'?",
    options: ["Städte", "Stätte", "Stadte", "Stadts"],
    correctAnswer: "Städte",
    explanation: "Die Mehrzahl von Stadt ist Städte (Umlaut + e)", xpReward: 5 },
  { id: "pl-strasse", category: "plural", klasse: 3,
    prompt: "Was ist die Mehrzahl von 'Straße'?",
    options: ["Straßen", "Straßes", "Straszen", "Straße"],
    correctAnswer: "Straßen",
    explanation: "Die Mehrzahl von Straße ist Straßen", xpReward: 5 },
  { id: "pl-lehrer", category: "plural", klasse: 3,
    prompt: "Was ist die Mehrzahl von 'Lehrer'?",
    options: ["Lehrer", "Lehrers", "Lehrern", "Lehre"],
    correctAnswer: "Lehrer",
    explanation: "Die Mehrzahl von Lehrer ist Lehrer (keine Änderung)", xpReward: 5 },
  { id: "pl-fenster", category: "plural", klasse: 3,
    prompt: "Was ist die Mehrzahl von 'Fenster'?",
    options: ["Fenster", "Fenstern", "Fenstere", "Fensters"],
    correctAnswer: "Fenster",
    explanation: "Die Mehrzahl von Fenster ist Fenster (keine Änderung)", xpReward: 5 },
  // Klasse 4
  { id: "pl-zeitung", category: "plural", klasse: 4,
    prompt: "Was ist die Mehrzahl von 'Zeitung'?",
    options: ["Zeitungen", "Zeitungs", "Zeitung", "Zeitünge"],
    correctAnswer: "Zeitungen",
    explanation: "Die Mehrzahl von Zeitung ist Zeitungen", xpReward: 5 },
  { id: "pl-erfindung", category: "plural", klasse: 4,
    prompt: "Was ist die Mehrzahl von 'Erfindung'?",
    options: ["Erfindungen", "Erfindungs", "Erfindunge", "Erfindüngen"],
    correctAnswer: "Erfindungen",
    explanation: "Wörter auf -ung bilden die Mehrzahl mit -en", xpReward: 5 },
];

// ─── D) Adjektiv Steigerung (22 exercises, Klasse 2–4) ───────────────────────

export const adjectiveComparisonExercises: GrammarExercise[] = [
  { id: "ac-klein", category: "adjective-comparison", klasse: 3,
    prompt: "klein → kleiner → ___",
    options: ["am kleinsten", "am kleines", "kleinstes", "kleinste"],
    correctAnswer: "am kleinsten",
    explanation: "Superlativ: am klein-sten", xpReward: 5 },
  { id: "ac-gross", category: "adjective-comparison", klasse: 3,
    prompt: "groß → größer → ___",
    options: ["am größten", "am großsten", "größtes", "am großen"],
    correctAnswer: "am größten",
    explanation: "Superlativ mit Umlaut: am größ-ten", xpReward: 5 },
  { id: "ac-schnell", category: "adjective-comparison", klasse: 3,
    prompt: "schnell → schneller → ___",
    options: ["am schnellsten", "am schnellen", "schnellstes", "am schnelleres"],
    correctAnswer: "am schnellsten",
    explanation: "Superlativ: am schnell-sten", xpReward: 5 },
  { id: "ac-langsam", category: "adjective-comparison", klasse: 3,
    prompt: "langsam → langsamer → ___",
    options: ["am langsamsten", "am langsamen", "langsamsten", "am langsameren"],
    correctAnswer: "am langsamsten",
    explanation: "Superlativ: am langsam-sten", xpReward: 5 },
  { id: "ac-schoen", category: "adjective-comparison", klasse: 3,
    prompt: "schön → schöner → ___",
    options: ["am schönsten", "am schönen", "schönstes", "am schöneres"],
    correctAnswer: "am schönsten",
    explanation: "Superlativ: am schön-sten", xpReward: 5 },
  { id: "ac-alt", category: "adjective-comparison", klasse: 3,
    prompt: "alt → älter → ___",
    options: ["am ältesten", "am alten", "am ältsten", "ältest"],
    correctAnswer: "am ältesten",
    explanation: "Superlativ mit Umlaut und -esten: am älte-sten", xpReward: 5 },
  { id: "ac-jung", category: "adjective-comparison", klasse: 3,
    prompt: "jung → jünger → ___",
    options: ["am jüngsten", "am jungen", "jüngstes", "am jüngeren"],
    correctAnswer: "am jüngsten",
    explanation: "Superlativ mit Umlaut: am jüng-sten", xpReward: 5 },
  { id: "ac-warm", category: "adjective-comparison", klasse: 3,
    prompt: "warm → wärmer → ___",
    options: ["am wärmsten", "am warmen", "wärmstes", "am wärmeren"],
    correctAnswer: "am wärmsten",
    explanation: "Superlativ mit Umlaut: am wärm-sten", xpReward: 5 },
  { id: "ac-kalt", category: "adjective-comparison", klasse: 3,
    prompt: "kalt → kälter → ___",
    options: ["am kältesten", "am kalten", "am kältsten", "kältest"],
    correctAnswer: "am kältesten",
    explanation: "Superlativ mit Umlaut: am kälte-sten", xpReward: 5 },
  { id: "ac-laut", category: "adjective-comparison", klasse: 3,
    prompt: "laut → lauter → ___",
    options: ["am lautesten", "am lauten", "lautstes", "am lautersten"],
    correctAnswer: "am lautesten",
    explanation: "Superlativ: am laut-esten (mit e)", xpReward: 5 },
  { id: "ac-stark", category: "adjective-comparison", klasse: 3,
    prompt: "stark → stärker → ___",
    options: ["am stärksten", "am starken", "stärkstes", "am stärkeren"],
    correctAnswer: "am stärksten",
    explanation: "Superlativ mit Umlaut: am stärk-sten", xpReward: 5 },
  { id: "ac-schwach", category: "adjective-comparison", klasse: 3,
    prompt: "schwach → schwächer → ___",
    options: ["am schwächsten", "am schwachen", "schwächstes", "am schwächeren"],
    correctAnswer: "am schwächsten",
    explanation: "Superlativ mit Umlaut: am schwäch-sten", xpReward: 5 },
  { id: "ac-hell", category: "adjective-comparison", klasse: 3,
    prompt: "hell → heller → ___",
    options: ["am hellsten", "am hellen", "hellstes", "am helleres"],
    correctAnswer: "am hellsten",
    explanation: "Superlativ: am hell-sten", xpReward: 5 },
  { id: "ac-dunkel", category: "adjective-comparison", klasse: 3,
    prompt: "dunkel → dunkler → ___",
    options: ["am dunkelsten", "am dunklen", "dunkelstes", "am dunkleren"],
    correctAnswer: "am dunkelsten",
    explanation: "Superlativ: am dunkel-sten", xpReward: 5 },
  { id: "ac-lang", category: "adjective-comparison", klasse: 3,
    prompt: "lang → länger → ___",
    options: ["am längsten", "am langen", "längstes", "am längersten"],
    correctAnswer: "am längsten",
    explanation: "Superlativ mit Umlaut: am läng-sten", xpReward: 5 },
  { id: "ac-kurz", category: "adjective-comparison", klasse: 3,
    prompt: "kurz → kürzer → ___",
    options: ["am kürzesten", "am kurzen", "kürzestes", "am kürzsten"],
    correctAnswer: "am kürzesten",
    explanation: "Superlativ mit Umlaut: am kürze-sten", xpReward: 5 },
  { id: "ac-dick", category: "adjective-comparison", klasse: 3,
    prompt: "dick → dicker → ___",
    options: ["am dicksten", "am dicken", "dickstes", "am dickeren"],
    correctAnswer: "am dicksten",
    explanation: "Superlativ: am dick-sten", xpReward: 5 },
  { id: "ac-duenn", category: "adjective-comparison", klasse: 3,
    prompt: "dünn → dünner → ___",
    options: ["am dünnsten", "am dünnen", "dünnstes", "am dünneren"],
    correctAnswer: "am dünnsten",
    explanation: "Superlativ: am dünn-sten", xpReward: 5 },
  { id: "ac-hoch", category: "adjective-comparison", klasse: 4,
    prompt: "hoch → höher → ___",
    options: ["am höchsten", "am hohen", "am höhsten", "höchstes"],
    correctAnswer: "am höchsten",
    explanation: "Unregelmäßig: hoch → höher → am höch-sten", xpReward: 5 },
  { id: "ac-gut", category: "adjective-comparison", klasse: 4,
    prompt: "gut → besser → ___",
    options: ["am besten", "am gutsten", "am besseren", "gut-sten"],
    correctAnswer: "am besten",
    explanation: "Sehr unregelmäßig: gut → besser → am besten", xpReward: 5 },
  { id: "ac-viel", category: "adjective-comparison", klasse: 4,
    prompt: "viel → mehr → ___",
    options: ["am meisten", "am vielsten", "am mehrsten", "am vielen"],
    correctAnswer: "am meisten",
    explanation: "Sehr unregelmäßig: viel → mehr → am meisten", xpReward: 5 },
  { id: "ac-leise", category: "adjective-comparison", klasse: 3,
    prompt: "leise → leiser → ___",
    options: ["am leisesten", "am leisen", "leisestem", "am leisersten"],
    correctAnswer: "am leisesten",
    explanation: "Superlativ: am leise-sten", xpReward: 5 },
];

// ─── E) Satzzeichen (25 exercises, Klasse 1–4) ───────────────────────────────

export const punctuationExercises: GrammarExercise[] = [
  // Klasse 1 — nur Punkt (Aussagesätze)
  { id: "sz-2", category: "punctuation", klasse: 1,
    prompt: "Die Sonne scheint heute ___",
    options: [".", "?", "!"],
    correctAnswer: ".",
    explanation: "Das ist eine Aussage → Punkt", xpReward: 5 },
  { id: "sz-5", category: "punctuation", klasse: 1,
    prompt: "Der Hund bellt laut ___",
    options: [".", "?", "!"],
    correctAnswer: ".",
    explanation: "Das ist eine Aussage → Punkt", xpReward: 5 },
  // Klasse 2 — Punkt + Fragezeichen
  { id: "sz-1", category: "punctuation", klasse: 2,
    prompt: "Wie heißt du ___",
    options: ["?", ".", "!"],
    correctAnswer: "?",
    explanation: "Das ist eine Frage → Fragezeichen", xpReward: 5 },
  { id: "sz-4", category: "punctuation", klasse: 2,
    prompt: "Wo wohnst du ___",
    options: ["?", ".", "!"],
    correctAnswer: "?",
    explanation: "Das ist eine Frage → Fragezeichen", xpReward: 5 },
  // Klasse 3 — Ausrufezeichen kommt hinzu
  { id: "sz-3", category: "punctuation", klasse: 3,
    prompt: "Pass auf ___",
    options: ["!", ".", "?"],
    correctAnswer: "!",
    explanation: "Das ist ein Ausruf → Ausrufezeichen", xpReward: 5 },
  { id: "sz-6", category: "punctuation", klasse: 3,
    prompt: "Komm bitte sofort her ___",
    options: ["!", ".", "?"],
    correctAnswer: "!",
    explanation: "Eine Aufforderung → Ausrufezeichen", xpReward: 5 },
  { id: "sz-7", category: "punctuation", klasse: 2,
    prompt: "Heute ist Montag ___",
    options: [".", "?", "!"],
    correctAnswer: ".",
    explanation: "Das ist eine Aussage → Punkt", xpReward: 5 },
  { id: "sz-8", category: "punctuation", klasse: 2,
    prompt: "Hast du Hunger ___",
    options: ["?", ".", "!"],
    correctAnswer: "?",
    explanation: "Das ist eine Frage → Fragezeichen", xpReward: 5 },
  { id: "sz-9", category: "punctuation", klasse: 3,
    prompt: "Das ist wunderbar ___",
    options: ["!", ".", "?"],
    correctAnswer: "!",
    explanation: "Das ist ein Ausruf → Ausrufezeichen", xpReward: 5 },
  { id: "sz-10", category: "punctuation", klasse: 2,
    prompt: "Wann kommst du nach Hause ___",
    options: ["?", ".", "!"],
    correctAnswer: "?",
    explanation: "Das ist eine Frage → Fragezeichen", xpReward: 5 },
  { id: "sz-11", category: "punctuation", klasse: 2,
    prompt: "Das Wetter ist heute sehr schön ___",
    options: [".", "?", "!"],
    correctAnswer: ".",
    explanation: "Das ist eine Aussage → Punkt", xpReward: 5 },
  { id: "sz-12", category: "punctuation", klasse: 3,
    prompt: "Vorsicht, das ist heiß ___",
    options: ["!", ".", "?"],
    correctAnswer: "!",
    explanation: "Eine Warnung → Ausrufezeichen", xpReward: 5 },
  { id: "sz-13", category: "punctuation", klasse: 2,
    prompt: "Warum bist du traurig ___",
    options: ["?", ".", "!"],
    correctAnswer: "?",
    explanation: "Das ist eine Frage → Fragezeichen", xpReward: 5 },
  // Klasse 3
  { id: "sz-14", category: "punctuation", klasse: 3,
    prompt: "Die Schule beginnt um acht Uhr ___",
    options: [".", "?", "!"],
    correctAnswer: ".",
    explanation: "Das ist eine Aussage → Punkt", xpReward: 5 },
  { id: "sz-15", category: "punctuation", klasse: 3,
    prompt: "Wie lange dauert die Reise ___",
    options: ["?", ".", "!"],
    correctAnswer: "?",
    explanation: "Das ist eine Frage → Fragezeichen", xpReward: 5 },
  { id: "sz-16", category: "punctuation", klasse: 3,
    prompt: "Das haben wir super geschafft ___",
    options: ["!", ".", "?"],
    correctAnswer: "!",
    explanation: "Das ist ein Ausruf → Ausrufezeichen", xpReward: 5 },
  { id: "sz-17", category: "punctuation", klasse: 3,
    prompt: "Wer hat das Fenster aufgemacht ___",
    options: ["?", ".", "!"],
    correctAnswer: "?",
    explanation: "Das ist eine Frage → Fragezeichen", xpReward: 5 },
  { id: "sz-18", category: "punctuation", klasse: 3,
    prompt: "Es schneit draußen sehr stark ___",
    options: [".", "?", "!"],
    correctAnswer: ".",
    explanation: "Das ist eine Aussage → Punkt", xpReward: 5 },
  { id: "sz-19", category: "punctuation", klasse: 3,
    prompt: "Hurra, wir haben gewonnen ___",
    options: ["!", ".", "?"],
    correctAnswer: "!",
    explanation: "Das ist ein Freudenschrei → Ausrufezeichen", xpReward: 5 },
  { id: "sz-20", category: "punctuation", klasse: 3,
    prompt: "Wie weit ist es noch bis dahin ___",
    options: ["?", ".", "!"],
    correctAnswer: "?",
    explanation: "Das ist eine Frage → Fragezeichen", xpReward: 5 },
  // Klasse 4
  { id: "sz-21", category: "punctuation", klasse: 4,
    prompt: "Die Aufgaben müssen bis morgen fertig sein ___",
    options: [".", "?", "!"],
    correctAnswer: ".",
    explanation: "Das ist eine Aussage → Punkt", xpReward: 5 },
  { id: "sz-22", category: "punctuation", klasse: 4,
    prompt: "Welche Lösung ist die richtige ___",
    options: ["?", ".", "!"],
    correctAnswer: "?",
    explanation: "Das ist eine Frage → Fragezeichen", xpReward: 5 },
  { id: "sz-23", category: "punctuation", klasse: 4,
    prompt: "Das ist eine unglaubliche Leistung ___",
    options: ["!", ".", "?"],
    correctAnswer: "!",
    explanation: "Das ist ein Ausruf der Begeisterung → Ausrufezeichen", xpReward: 5 },
  { id: "sz-24", category: "punctuation", klasse: 4,
    prompt: "Wann wurde die Druckerpresse erfunden ___",
    options: ["?", ".", "!"],
    correctAnswer: "?",
    explanation: "Das ist eine Frage → Fragezeichen", xpReward: 5 },
  { id: "sz-25", category: "punctuation", klasse: 4,
    prompt: "Der Regenwald ist für das Klima sehr wichtig ___",
    options: [".", "?", "!"],
    correctAnswer: ".",
    explanation: "Das ist eine Aussage → Punkt", xpReward: 5 },
];

// ─── F) Großschreibung (25 exercises, Klasse 1–4) ────────────────────────────

export const capitalizationExercises: GrammarExercise[] = [
  // Klasse 1
  { id: "gs-1", category: "capitalization", klasse: 1,
    prompt: "Das kleine mädchen spielt im Garten.",
    options: ["mädchen", "Mädchen"],
    correctAnswer: "Mädchen",
    explanation: "Nomen schreibt man groß: das Mädchen", xpReward: 5 },
  { id: "gs-2", category: "capitalization", klasse: 1,
    prompt: "Der hund bellt sehr laut.",
    options: ["hund", "Hund"],
    correctAnswer: "Hund",
    explanation: "Nomen schreibt man groß: der Hund", xpReward: 5 },
  { id: "gs-3", category: "capitalization", klasse: 1,
    prompt: "Meine katze schläft auf dem Sofa.",
    options: ["katze", "Katze"],
    correctAnswer: "Katze",
    explanation: "Nomen schreibt man groß: die Katze", xpReward: 5 },
  { id: "gs-4", category: "capitalization", klasse: 1,
    prompt: "Wir gehen in die schule.",
    options: ["schule", "Schule"],
    correctAnswer: "Schule",
    explanation: "Nomen schreibt man groß: die Schule", xpReward: 5 },
  { id: "gs-5", category: "capitalization", klasse: 1,
    prompt: "Der ball rollt über die Straße.",
    options: ["ball", "Ball"],
    correctAnswer: "Ball",
    explanation: "Nomen schreibt man groß: der Ball", xpReward: 5 },
  // Klasse 2
  { id: "gs-6", category: "capitalization", klasse: 2,
    prompt: "Die blume ist sehr schön.",
    options: ["blume", "Blume"],
    correctAnswer: "Blume",
    explanation: "Nomen schreibt man groß: die Blume", xpReward: 5 },
  { id: "gs-7", category: "capitalization", klasse: 2,
    prompt: "Das buch liegt auf dem Tisch.",
    options: ["buch", "Buch"],
    correctAnswer: "Buch",
    explanation: "Nomen schreibt man groß: das Buch", xpReward: 5 },
  { id: "gs-8", category: "capitalization", klasse: 2,
    prompt: "Wir fahren ans meer.",
    options: ["meer", "Meer"],
    correctAnswer: "Meer",
    explanation: "Nomen schreibt man groß: das Meer", xpReward: 5 },
  { id: "gs-9", category: "capitalization", klasse: 2,
    prompt: "Der vogel singt ein schönes Lied.",
    options: ["vogel", "Vogel"],
    correctAnswer: "Vogel",
    explanation: "Nomen schreibt man groß: der Vogel", xpReward: 5 },
  { id: "gs-10", category: "capitalization", klasse: 2,
    prompt: "Ich trinke jeden Tag viel wasser.",
    options: ["wasser", "Wasser"],
    correctAnswer: "Wasser",
    explanation: "Nomen schreibt man groß: das Wasser", xpReward: 5 },
  { id: "gs-11", category: "capitalization", klasse: 2,
    prompt: "Das auto fährt sehr schnell.",
    options: ["auto", "Auto"],
    correctAnswer: "Auto",
    explanation: "Nomen schreibt man groß: das Auto", xpReward: 5 },
  // Klasse 3
  { id: "gs-12", category: "capitalization", klasse: 3,
    prompt: "Der berg ist sehr hoch.",
    options: ["berg", "Berg"],
    correctAnswer: "Berg",
    explanation: "Nomen schreibt man groß: der Berg", xpReward: 5 },
  { id: "gs-13", category: "capitalization", klasse: 3,
    prompt: "Die stadt hat einen großen Park.",
    options: ["stadt", "Stadt"],
    correctAnswer: "Stadt",
    explanation: "Nomen schreibt man groß: die Stadt", xpReward: 5 },
  { id: "gs-14", category: "capitalization", klasse: 3,
    prompt: "Das wasser im Fluss ist kalt.",
    options: ["wasser", "Wasser"],
    correctAnswer: "Wasser",
    explanation: "Nomen schreibt man groß: das Wasser", xpReward: 5 },
  { id: "gs-15", category: "capitalization", klasse: 3,
    prompt: "Die sonne scheint heute hell.",
    options: ["sonne", "Sonne"],
    correctAnswer: "Sonne",
    explanation: "Nomen schreibt man groß: die Sonne", xpReward: 5 },
  { id: "gs-16", category: "capitalization", klasse: 3,
    prompt: "Der wald ist dunkel und groß.",
    options: ["wald", "Wald"],
    correctAnswer: "Wald",
    explanation: "Nomen schreibt man groß: der Wald", xpReward: 5 },
  { id: "gs-17", category: "capitalization", klasse: 3,
    prompt: "Ein freund hilft dir immer.",
    options: ["freund", "Freund"],
    correctAnswer: "Freund",
    explanation: "Nomen schreibt man groß: der Freund", xpReward: 5 },
  { id: "gs-18", category: "capitalization", klasse: 3,
    prompt: "Im frühling blühen die Blumen.",
    options: ["frühling", "Frühling"],
    correctAnswer: "Frühling",
    explanation: "Nomen schreibt man groß: der Frühling", xpReward: 5 },
  // Klasse 4
  { id: "gs-19", category: "capitalization", klasse: 4,
    prompt: "Die wissenschaft hilft uns allen.",
    options: ["wissenschaft", "Wissenschaft"],
    correctAnswer: "Wissenschaft",
    explanation: "Nomen schreibt man groß: die Wissenschaft", xpReward: 5 },
  { id: "gs-20", category: "capitalization", klasse: 4,
    prompt: "Das erfinden neuer Dinge macht Spaß.",
    options: ["erfinden", "Erfinden"],
    correctAnswer: "Erfinden",
    explanation: "Infinitiv als Nomen (substantiviert) → großgeschrieben: das Erfinden", xpReward: 5 },
  { id: "gs-21", category: "capitalization", klasse: 4,
    prompt: "Die demokratie ist wichtig für unser Land.",
    options: ["demokratie", "Demokratie"],
    correctAnswer: "Demokratie",
    explanation: "Nomen schreibt man groß: die Demokratie", xpReward: 5 },
  { id: "gs-22", category: "capitalization", klasse: 4,
    prompt: "Der umweltschutz ist eine große Aufgabe.",
    options: ["umweltschutz", "Umweltschutz"],
    correctAnswer: "Umweltschutz",
    explanation: "Zusammengesetzte Nomen schreibt man groß: der Umweltschutz", xpReward: 5 },
  { id: "gs-23", category: "capitalization", klasse: 3,
    prompt: "Der winter ist kalt und schneereich.",
    options: ["winter", "Winter"],
    correctAnswer: "Winter",
    explanation: "Nomen schreibt man groß: der Winter", xpReward: 5 },
  { id: "gs-24", category: "capitalization", klasse: 2,
    prompt: "Mein bruder ist sehr lustig.",
    options: ["bruder", "Bruder"],
    correctAnswer: "Bruder",
    explanation: "Nomen schreibt man groß: der Bruder", xpReward: 5 },
  { id: "gs-25", category: "capitalization", klasse: 3,
    prompt: "Die natur ist wunderschön.",
    options: ["natur", "Natur"],
    correctAnswer: "Natur",
    explanation: "Nomen schreibt man groß: die Natur", xpReward: 5 },
];

// ─── G) Wortarten erkennen (30 exercises, Klasse 1–4) ────────────────────────

export const wordTypeExercises: GrammarExercise[] = [
  // Verben — ab Klasse 3
  { id: "wa-spielen", category: "word-types", klasse: 3,
    prompt: "spielen",
    options: ["Nomen", "Verb", "Adjektiv", "Artikel"],
    correctAnswer: "Verb",
    explanation: "'spielen' ist ein Verb (Tätigkeitswort)", xpReward: 5 },
  { id: "wa-laufen", category: "word-types", klasse: 3,
    prompt: "laufen",
    options: ["Nomen", "Verb", "Adjektiv", "Artikel"],
    correctAnswer: "Verb",
    explanation: "'laufen' ist ein Verb (Tätigkeitswort)", xpReward: 5 },
  { id: "wa-schreiben", category: "word-types", klasse: 3,
    prompt: "schreiben",
    options: ["Nomen", "Verb", "Adjektiv", "Artikel"],
    correctAnswer: "Verb",
    explanation: "'schreiben' ist ein Verb (Tätigkeitswort)", xpReward: 5 },
  { id: "wa-essen", category: "word-types", klasse: 3,
    prompt: "essen",
    options: ["Nomen", "Verb", "Adjektiv", "Artikel"],
    correctAnswer: "Verb",
    explanation: "'essen' ist ein Verb (Tätigkeitswort)", xpReward: 5 },
  { id: "wa-schlafen", category: "word-types", klasse: 3,
    prompt: "schlafen",
    options: ["Nomen", "Verb", "Adjektiv", "Artikel"],
    correctAnswer: "Verb",
    explanation: "'schlafen' ist ein Verb (Tätigkeitswort)", xpReward: 5 },
  { id: "wa-denken", category: "word-types", klasse: 3,
    prompt: "denken",
    options: ["Nomen", "Verb", "Adjektiv", "Artikel"],
    correctAnswer: "Verb",
    explanation: "'denken' ist ein Verb (Tätigkeitswort)", xpReward: 5 },
  { id: "wa-singen", category: "word-types", klasse: 3,
    prompt: "singen",
    options: ["Nomen", "Verb", "Adjektiv", "Artikel"],
    correctAnswer: "Verb",
    explanation: "'singen' ist ein Verb (Tätigkeitswort)", xpReward: 5 },
  { id: "wa-arbeiten", category: "word-types", klasse: 3,
    prompt: "arbeiten",
    options: ["Nomen", "Verb", "Adjektiv", "Artikel"],
    correctAnswer: "Verb",
    explanation: "'arbeiten' ist ein Verb (Tätigkeitswort)", xpReward: 5 },
  { id: "wa-fliegen", category: "word-types", klasse: 3,
    prompt: "fliegen",
    options: ["Nomen", "Verb", "Adjektiv", "Artikel"],
    correctAnswer: "Verb",
    explanation: "'fliegen' ist ein Verb (Tätigkeitswort)", xpReward: 5 },
  { id: "wa-helfen", category: "word-types", klasse: 3,
    prompt: "helfen",
    options: ["Nomen", "Verb", "Adjektiv", "Artikel"],
    correctAnswer: "Verb",
    explanation: "'helfen' ist ein Verb (Tätigkeitswort)", xpReward: 5 },
  // Adjektive — ab Klasse 4
  { id: "wa-schoen-adj", category: "word-types", klasse: 4,
    prompt: "schön",
    options: ["Nomen", "Verb", "Adjektiv", "Artikel"],
    correctAnswer: "Adjektiv",
    explanation: "'schön' ist ein Adjektiv (Eigenschaftswort)", xpReward: 5 },
  { id: "wa-gross-adj", category: "word-types", klasse: 4,
    prompt: "groß",
    options: ["Nomen", "Verb", "Adjektiv", "Artikel"],
    correctAnswer: "Adjektiv",
    explanation: "'groß' ist ein Adjektiv (Eigenschaftswort)", xpReward: 5 },
  { id: "wa-klein-adj", category: "word-types", klasse: 4,
    prompt: "klein",
    options: ["Nomen", "Verb", "Adjektiv", "Artikel"],
    correctAnswer: "Adjektiv",
    explanation: "'klein' ist ein Adjektiv (Eigenschaftswort)", xpReward: 5 },
  { id: "wa-schnell-adj", category: "word-types", klasse: 4,
    prompt: "schnell",
    options: ["Nomen", "Verb", "Adjektiv", "Artikel"],
    correctAnswer: "Adjektiv",
    explanation: "'schnell' ist ein Adjektiv (Eigenschaftswort)", xpReward: 5 },
  { id: "wa-traurig", category: "word-types", klasse: 4,
    prompt: "traurig",
    options: ["Nomen", "Verb", "Adjektiv", "Artikel"],
    correctAnswer: "Adjektiv",
    explanation: "'traurig' ist ein Adjektiv (Eigenschaftswort)", xpReward: 5 },
  { id: "wa-gluecklich", category: "word-types", klasse: 4,
    prompt: "glücklich",
    options: ["Nomen", "Verb", "Adjektiv", "Artikel"],
    correctAnswer: "Adjektiv",
    explanation: "'glücklich' ist ein Adjektiv (Eigenschaftswort)", xpReward: 5 },
  { id: "wa-interessant", category: "word-types", klasse: 4,
    prompt: "interessant",
    options: ["Nomen", "Verb", "Adjektiv", "Artikel"],
    correctAnswer: "Adjektiv",
    explanation: "'interessant' ist ein Adjektiv (Eigenschaftswort)", xpReward: 5 },
  { id: "wa-lecker", category: "word-types", klasse: 4,
    prompt: "lecker",
    options: ["Nomen", "Verb", "Adjektiv", "Artikel"],
    correctAnswer: "Adjektiv",
    explanation: "'lecker' ist ein Adjektiv (Eigenschaftswort)", xpReward: 5 },
  // Nomen — ab Klasse 3
  { id: "wa-hund-n", category: "word-types", klasse: 3,
    prompt: "Hund",
    options: ["Nomen", "Verb", "Adjektiv", "Artikel"],
    correctAnswer: "Nomen",
    explanation: "'Hund' ist ein Nomen (Namenwort) — man erkennt es am großen Anfangsbuchstaben", xpReward: 5 },
  { id: "wa-schule-n", category: "word-types", klasse: 3,
    prompt: "Schule",
    options: ["Nomen", "Verb", "Adjektiv", "Artikel"],
    correctAnswer: "Nomen",
    explanation: "'Schule' ist ein Nomen (Namenwort)", xpReward: 5 },
  { id: "wa-freundschaft", category: "word-types", klasse: 3,
    prompt: "Freundschaft",
    options: ["Nomen", "Verb", "Adjektiv", "Artikel"],
    correctAnswer: "Nomen",
    explanation: "'Freundschaft' ist ein Nomen (Namenwort)", xpReward: 5 },
  { id: "wa-baum-n", category: "word-types", klasse: 3,
    prompt: "Baum",
    options: ["Nomen", "Verb", "Adjektiv", "Artikel"],
    correctAnswer: "Nomen",
    explanation: "'Baum' ist ein Nomen (Namenwort)", xpReward: 5 },
  { id: "wa-musik", category: "word-types", klasse: 3,
    prompt: "Musik",
    options: ["Nomen", "Verb", "Adjektiv", "Artikel"],
    correctAnswer: "Nomen",
    explanation: "'Musik' ist ein Nomen (Namenwort)", xpReward: 5 },
  { id: "wa-abenteuer", category: "word-types", klasse: 3,
    prompt: "Abenteuer",
    options: ["Nomen", "Verb", "Adjektiv", "Artikel"],
    correctAnswer: "Nomen",
    explanation: "'Abenteuer' ist ein Nomen (Namenwort)", xpReward: 5 },
  { id: "wa-wissenschaft", category: "word-types", klasse: 4,
    prompt: "Wissenschaft",
    options: ["Nomen", "Verb", "Adjektiv", "Artikel"],
    correctAnswer: "Nomen",
    explanation: "'Wissenschaft' ist ein Nomen (Namenwort)", xpReward: 5 },
  // Artikel — ab Klasse 4
  { id: "wa-der", category: "word-types", klasse: 4,
    prompt: "der",
    options: ["Nomen", "Verb", "Adjektiv", "Artikel"],
    correctAnswer: "Artikel",
    explanation: "'der' ist ein Artikel (Begleitwort des Nomens)", xpReward: 5 },
  { id: "wa-die", category: "word-types", klasse: 4,
    prompt: "die",
    options: ["Nomen", "Verb", "Adjektiv", "Artikel"],
    correctAnswer: "Artikel",
    explanation: "'die' ist ein Artikel (Begleitwort des Nomens)", xpReward: 5 },
  { id: "wa-das", category: "word-types", klasse: 4,
    prompt: "das",
    options: ["Nomen", "Verb", "Adjektiv", "Artikel"],
    correctAnswer: "Artikel",
    explanation: "'das' ist ein Artikel (Begleitwort des Nomens)", xpReward: 5 },
  { id: "wa-ein", category: "word-types", klasse: 4,
    prompt: "ein",
    options: ["Nomen", "Verb", "Adjektiv", "Artikel"],
    correctAnswer: "Artikel",
    explanation: "'ein' ist ein unbestimmter Artikel", xpReward: 5 },
  { id: "wa-eine", category: "word-types", klasse: 4,
    prompt: "eine",
    options: ["Nomen", "Verb", "Adjektiv", "Artikel"],
    correctAnswer: "Artikel",
    explanation: "'eine' ist ein unbestimmter Artikel (weiblich)", xpReward: 5 },
];

// ─── H) Satzbau (20 exercises, Klasse 2–4) ───────────────────────────────────

export const sentenceBuildingExercises: GrammarExercise[] = [
  { id: "sb-1", category: "sentence-building", klasse: 3,
    prompt: "Wörter: Hund – bellt – Der – laut",
    options: ["Der Hund bellt laut.", "Bellt der Hund laut?", "Laut Der bellt Hund."],
    correctAnswer: "Der Hund bellt laut.",
    explanation: "Aussagesatz: Subjekt (Der Hund) + Verb (bellt) + Rest", xpReward: 5 },
  { id: "sb-2", category: "sentence-building", klasse: 3,
    prompt: "Wörter: gern – Ich – lese – Bücher",
    options: ["Ich lese gern Bücher.", "Bücher lese ich gern?", "Ich gern Bücher lese."],
    correctAnswer: "Ich lese gern Bücher.",
    explanation: "Das Verb steht auf Platz 2: Ich lese …", xpReward: 5 },
  { id: "sb-3", category: "sentence-building", klasse: 3,
    prompt: "Wörter: spielen – Kinder – Die – im – Garten",
    options: ["Die Kinder spielen im Garten.", "Im Garten spielen die Kinder.", "Kinder im Garten die spielen."],
    correctAnswer: "Die Kinder spielen im Garten.",
    explanation: "Beides wäre möglich, aber diese Reihenfolge ist am natürlichsten", xpReward: 5 },
  { id: "sb-4", category: "sentence-building", klasse: 3,
    prompt: "Wörter: schläft – Katze – Die – Sofa – auf dem",
    options: ["Die Katze schläft auf dem Sofa.", "Auf dem Sofa die Katze schläft.", "Die schläft Katze auf dem Sofa."],
    correctAnswer: "Die Katze schläft auf dem Sofa.",
    explanation: "Verb auf Platz 2: Die Katze schläft …", xpReward: 5 },
  { id: "sb-5", category: "sentence-building", klasse: 3,
    prompt: "Wörter: Mutter – kauft – Brot – Meine",
    options: ["Meine Mutter kauft Brot.", "Brot kauft meine Mutter.", "Kauft Meine Mutter Brot?"],
    correctAnswer: "Meine Mutter kauft Brot.",
    explanation: "Aussagesatz: Subjekt + Verb + Objekt", xpReward: 5 },
  { id: "sb-6", category: "sentence-building", klasse: 3,
    prompt: "Wörter: Heute – scheint – Sonne – die",
    options: ["Heute scheint die Sonne.", "Die Sonne scheint heute.", "Scheint heute die Sonne?"],
    correctAnswer: "Heute scheint die Sonne.",
    explanation: "Wenn ein Zeitausdruck vorne steht, kommt das Verb auf Platz 2", xpReward: 5 },
  { id: "sb-7", category: "sentence-building", klasse: 3,
    prompt: "Wörter: hat – Das – Kind – Hunger",
    options: ["Das Kind hat Hunger.", "Hunger hat das Kind.", "Das hat Kind Hunger."],
    correctAnswer: "Das Kind hat Hunger.",
    explanation: "Verb auf Platz 2: Das Kind hat …", xpReward: 5 },
  { id: "sb-8", category: "sentence-building", klasse: 3,
    prompt: "Wörter: singen – Die – Vögel – im – Frühling",
    options: ["Die Vögel singen im Frühling.", "Im Frühling die Vögel singen.", "Die singen Vögel im Frühling."],
    correctAnswer: "Die Vögel singen im Frühling.",
    explanation: "Verb auf Platz 2: Die Vögel singen …", xpReward: 5 },
  { id: "sb-9", category: "sentence-building", klasse: 3,
    prompt: "Wörter: Bruder – mir – Mein – hilft",
    options: ["Mein Bruder hilft mir.", "Mir hilft mein Bruder.", "Hilft mein Bruder mir?"],
    correctAnswer: "Mein Bruder hilft mir.",
    explanation: "Verb auf Platz 2: Mein Bruder hilft …", xpReward: 5 },
  { id: "sb-10", category: "sentence-building", klasse: 3,
    prompt: "Wörter: trinkt – gern – Er – kaltes – Wasser",
    options: ["Er trinkt gern kaltes Wasser.", "Kaltes Wasser trinkt er gern.", "Er gern trinkt kaltes Wasser."],
    correctAnswer: "Er trinkt gern kaltes Wasser.",
    explanation: "Verb auf Platz 2, Adverb danach: Er trinkt gern …", xpReward: 5 },
  { id: "sb-11", category: "sentence-building", klasse: 3,
    prompt: "Wörter: spielt – schön – Sie – Gitarre – sehr",
    options: ["Sie spielt sehr schön Gitarre.", "Gitarre spielt sie sehr schön.", "Sie sehr schön spielt Gitarre."],
    correctAnswer: "Sie spielt sehr schön Gitarre.",
    explanation: "Verb auf Platz 2: Sie spielt …", xpReward: 5 },
  { id: "sb-12", category: "sentence-building", klasse: 3,
    prompt: "Wörter: kommt – heute – er – Warum – nicht",
    options: ["Warum kommt er heute nicht?", "Er kommt warum heute nicht.", "Heute kommt er nicht warum?"],
    correctAnswer: "Warum kommt er heute nicht?",
    explanation: "Fragesatz mit Fragewort: Warum + Verb + Subjekt + Rest", xpReward: 5 },
  { id: "sb-13", category: "sentence-building", klasse: 3,
    prompt: "Wörter: schreibt – Sie – Hausaufgaben – ihre",
    options: ["Sie schreibt ihre Hausaufgaben.", "Ihre Hausaufgaben schreibt sie.", "Sie ihre Hausaufgaben schreibt."],
    correctAnswer: "Sie schreibt ihre Hausaufgaben.",
    explanation: "Verb auf Platz 2: Sie schreibt …", xpReward: 5 },
  { id: "sb-14", category: "sentence-building", klasse: 3,
    prompt: "Wörter: Zeitung – liest – der – Mann – die",
    options: ["Der Mann liest die Zeitung.", "Die Zeitung liest der Mann.", "Der liest Mann die Zeitung."],
    correctAnswer: "Der Mann liest die Zeitung.",
    explanation: "Verb auf Platz 2: Der Mann liest …", xpReward: 5 },
  { id: "sb-15", category: "sentence-building", klasse: 3,
    prompt: "Wörter: liegt – Boden – Der – auf dem – Hund",
    options: ["Der Hund liegt auf dem Boden.", "Auf dem Boden liegt der Hund.", "Der liegt Hund auf dem Boden."],
    correctAnswer: "Der Hund liegt auf dem Boden.",
    explanation: "Verb auf Platz 2: Der Hund liegt …", xpReward: 5 },
  { id: "sb-16", category: "sentence-building", klasse: 4,
    prompt: "Wörter: tolle – ist – Das – eine – Erfindung",
    options: ["Das ist eine tolle Erfindung.", "Eine tolle Erfindung ist das.", "Das eine tolle Erfindung ist."],
    correctAnswer: "Das ist eine tolle Erfindung.",
    explanation: "Verb auf Platz 2: Das ist …", xpReward: 5 },
  { id: "sb-17", category: "sentence-building", klasse: 4,
    prompt: "Wörter: Wasser – brauchen – sauberes – Wir",
    options: ["Wir brauchen sauberes Wasser.", "Sauberes Wasser brauchen wir.", "Wir sauberes Wasser brauchen."],
    correctAnswer: "Wir brauchen sauberes Wasser.",
    explanation: "Verb auf Platz 2: Wir brauchen …", xpReward: 5 },
  { id: "sb-18", category: "sentence-building", klasse: 4,
    prompt: "Wörter: wichtig – Wald – Der – sehr – ist",
    options: ["Der Wald ist sehr wichtig.", "Sehr wichtig ist der Wald.", "Der ist Wald sehr wichtig."],
    correctAnswer: "Der Wald ist sehr wichtig.",
    explanation: "Verb auf Platz 2: Der Wald ist …", xpReward: 5 },
  { id: "sb-19", category: "sentence-building", klasse: 4,
    prompt: "Wörter: erfand – Gutenberg – Druckerpresse – die",
    options: ["Gutenberg erfand die Druckerpresse.", "Die Druckerpresse erfand Gutenberg.", "Gutenberg die Druckerpresse erfand."],
    correctAnswer: "Gutenberg erfand die Druckerpresse.",
    explanation: "Verb auf Platz 2: Gutenberg erfand …", xpReward: 5 },
  { id: "sb-20", category: "sentence-building", klasse: 3,
    prompt: "Wörter: Park – Die – im – Kinder – spielen",
    options: ["Die Kinder spielen im Park.", "Im Park spielen die Kinder.", "Kinder die im Park spielen."],
    correctAnswer: "Die Kinder spielen im Park.",
    explanation: "Verb auf Platz 2: Die Kinder spielen …", xpReward: 5 },
];

// ─── I) Zeitformen — Präteritum (25 exercises, Klasse 3–4) ───────────────────

export const pastTenseExercises: GrammarExercise[] = [
  { id: "zt-sein-ich", category: "past-tense", klasse: 4,
    prompt: "Präsens: 'Ich bin müde.' → Präteritum: 'Ich ___'",
    options: ["war", "wäre", "bin", "wurde"],
    correctAnswer: "war",
    explanation: "'sein' im Präteritum: ich war", xpReward: 5 },
  { id: "zt-haben-er", category: "past-tense", klasse: 4,
    prompt: "Präsens: 'Er hat Hunger.' → Präteritum: 'Er ___'",
    options: ["hatte", "hat", "hätte", "habe"],
    correctAnswer: "hatte",
    explanation: "'haben' im Präteritum: er hatte", xpReward: 5 },
  { id: "zt-gehen-ich", category: "past-tense", klasse: 4,
    prompt: "Präsens: 'Ich gehe zur Schule.' → Präteritum: 'Ich ___'",
    options: ["ging", "gegangen", "geht", "gehe"],
    correctAnswer: "ging",
    explanation: "'gehen' im Präteritum: ich ging", xpReward: 5 },
  { id: "zt-kommen-sie", category: "past-tense", klasse: 4,
    prompt: "Präsens: 'Sie kommt nach Hause.' → Präteritum: 'Sie ___'",
    options: ["kam", "gekommen", "käme", "kommt"],
    correctAnswer: "kam",
    explanation: "'kommen' im Präteritum: sie kam", xpReward: 5 },
  { id: "zt-sehen-wir", category: "past-tense", klasse: 4,
    prompt: "Präsens: 'Wir sehen einen Film.' → Präteritum: 'Wir ___'",
    options: ["sahen", "sehen", "sähen", "gesehen"],
    correctAnswer: "sahen",
    explanation: "'sehen' im Präteritum: wir sahen", xpReward: 5 },
  { id: "zt-laufen-er", category: "past-tense", klasse: 4,
    prompt: "Präsens: 'Er läuft schnell.' → Präteritum: 'Er ___'",
    options: ["lief", "gelaufen", "läufte", "läuft"],
    correctAnswer: "lief",
    explanation: "'laufen' im Präteritum: er lief", xpReward: 5 },
  { id: "zt-essen-ich", category: "past-tense", klasse: 4,
    prompt: "Präsens: 'Ich esse Pizza.' → Präteritum: 'Ich ___'",
    options: ["aß", "gegessen", "aßte", "ißt"],
    correctAnswer: "aß",
    explanation: "'essen' im Präteritum: ich aß", xpReward: 5 },
  { id: "zt-schreiben-ich", category: "past-tense", klasse: 4,
    prompt: "Präsens: 'Ich schreibe einen Brief.' → Präteritum: 'Ich ___'",
    options: ["schrieb", "geschrieben", "schreibte", "schreibe"],
    correctAnswer: "schrieb",
    explanation: "'schreiben' im Präteritum: ich schrieb", xpReward: 5 },
  { id: "zt-lesen-sie", category: "past-tense", klasse: 4,
    prompt: "Präsens: 'Sie liest ein Buch.' → Präteritum: 'Sie ___'",
    options: ["las", "gelesen", "läste", "liest"],
    correctAnswer: "las",
    explanation: "'lesen' im Präteritum: sie las", xpReward: 5 },
  { id: "zt-liegen-hund", category: "past-tense", klasse: 4,
    prompt: "Präsens: 'Der Hund liegt auf dem Boden.' → Präteritum: 'Der Hund ___'",
    options: ["lag", "gelegen", "lagte", "liegt"],
    correctAnswer: "lag",
    explanation: "'liegen' im Präteritum: er lag", xpReward: 5 },
  { id: "zt-fahren-wir", category: "past-tense", klasse: 4,
    prompt: "Präsens: 'Wir fahren ans Meer.' → Präteritum: 'Wir ___'",
    options: ["fuhren", "gefahren", "fahrten", "fahren"],
    correctAnswer: "fuhren",
    explanation: "'fahren' im Präteritum: wir fuhren", xpReward: 5 },
  { id: "zt-schlafen-kind", category: "past-tense", klasse: 4,
    prompt: "Präsens: 'Das Kind schläft.' → Präteritum: 'Das Kind ___'",
    options: ["schlief", "geschlafen", "schläfte", "schläft"],
    correctAnswer: "schlief",
    explanation: "'schlafen' im Präteritum: es schlief", xpReward: 5 },
  { id: "zt-geben-er", category: "past-tense", klasse: 4,
    prompt: "Präsens: 'Er gibt mir das Buch.' → Präteritum: 'Er ___'",
    options: ["gab", "gegeben", "gäbe", "gibt"],
    correctAnswer: "gab",
    explanation: "'geben' im Präteritum: er gab", xpReward: 5 },
  { id: "zt-finden-sie", category: "past-tense", klasse: 4,
    prompt: "Präsens: 'Sie findet den Schlüssel.' → Präteritum: 'Sie ___'",
    options: ["fand", "gefunden", "findete", "findet"],
    correctAnswer: "fand",
    explanation: "'finden' im Präteritum: sie fand", xpReward: 5 },
  { id: "zt-denken-ich", category: "past-tense", klasse: 4,
    prompt: "Präsens: 'Ich denke nach.' → Präteritum: 'Ich ___'",
    options: ["dachte", "gedacht", "denkete", "denke"],
    correctAnswer: "dachte",
    explanation: "'denken' im Präteritum: ich dachte", xpReward: 5 },
  { id: "zt-stehen-wir", category: "past-tense", klasse: 4,
    prompt: "Präsens: 'Wir stehen früh auf.' → Präteritum: 'Wir ___'",
    options: ["standen", "gestanden", "stehten", "stehen"],
    correctAnswer: "standen",
    explanation: "'stehen' im Präteritum: wir standen", xpReward: 5 },
  { id: "zt-wissen-er", category: "past-tense", klasse: 4,
    prompt: "Präsens: 'Er weiß die Antwort.' → Präteritum: 'Er ___'",
    options: ["wusste", "gewusst", "wissete", "weiß"],
    correctAnswer: "wusste",
    explanation: "'wissen' im Präteritum: er wusste", xpReward: 5 },
  { id: "zt-bringen-sie", category: "past-tense", klasse: 4,
    prompt: "Präsens: 'Sie bringt Blumen mit.' → Präteritum: 'Sie ___'",
    options: ["brachte", "gebracht", "bringte", "bringt"],
    correctAnswer: "brachte",
    explanation: "'bringen' im Präteritum: sie brachte", xpReward: 5 },
  { id: "zt-nehmen-ich", category: "past-tense", klasse: 4,
    prompt: "Präsens: 'Ich nehme die Tasche.' → Präteritum: 'Ich ___'",
    options: ["nahm", "genommen", "nahmte", "nehme"],
    correctAnswer: "nahm",
    explanation: "'nehmen' im Präteritum: ich nahm", xpReward: 5 },
  { id: "zt-rufen-er", category: "past-tense", klasse: 4,
    prompt: "Präsens: 'Er ruft nach Hause.' → Präteritum: 'Er ___'",
    options: ["rief", "gerufen", "rufte", "ruft"],
    correctAnswer: "rief",
    explanation: "'rufen' im Präteritum: er rief", xpReward: 5 },
  { id: "zt-treffen-sie", category: "past-tense", klasse: 4,
    prompt: "Präsens: 'Sie trifft ihre Freunde.' → Präteritum: 'Sie ___'",
    options: ["traf", "getroffen", "traffte", "trifft"],
    correctAnswer: "traf",
    explanation: "'treffen' im Präteritum: sie traf", xpReward: 5 },
  { id: "zt-schwimmen-wir", category: "past-tense", klasse: 4,
    prompt: "Präsens: 'Wir schwimmen im See.' → Präteritum: 'Wir ___'",
    options: ["schwammen", "geschwommen", "schwimmten", "schwimmen"],
    correctAnswer: "schwammen",
    explanation: "'schwimmen' im Präteritum: wir schwammen", xpReward: 5 },
  { id: "zt-sprechen-er", category: "past-tense", klasse: 4,
    prompt: "Präsens: 'Er spricht Deutsch.' → Präteritum: 'Er ___'",
    options: ["sprach", "gesprochen", "sprachte", "spricht"],
    correctAnswer: "sprach",
    explanation: "'sprechen' im Präteritum: er sprach", xpReward: 5 },
  { id: "zt-trinken-du", category: "past-tense", klasse: 4,
    prompt: "Präsens: 'Du trinkst Wasser.' → Präteritum: 'Du ___'",
    options: ["trankst", "getrunken", "trinktest", "trinkst"],
    correctAnswer: "trankst",
    explanation: "'trinken' im Präteritum: du trankst", xpReward: 5 },
  { id: "zt-sein-wir", category: "past-tense", klasse: 4,
    prompt: "Präsens: 'Wir sind gute Freunde.' → Präteritum: 'Wir ___'",
    options: ["waren", "wären", "seien", "sind"],
    correctAnswer: "waren",
    explanation: "'sein' im Präteritum: wir waren", xpReward: 5 },
];

// ─── Vocabulary / Wortschatz (Synonyme, Klasse 1–4) ──────────────────────────

export const vocabularyExercises: GrammarExercise[] = [
  // ── Klasse 1 ────────────────────────────────────────────────────────────────
  { id: "voc-gross", category: "vocabulary", klasse: 1,
    prompt: "groß",
    options: ["riesig", "winzig", "bunt", "laut"],
    correctAnswer: "riesig",
    explanation: "Riesig bedeutet sehr groß – viel größer als normal!",
    vocabData: { emoji: "🏔️", definition: "Riesig heißt: unglaublich groß!", example: "Der Elefant ist riesig." },
    xpReward: 5 },
  { id: "voc-schnell", category: "vocabulary", klasse: 1,
    prompt: "schnell",
    options: ["langsam", "flink", "laut", "kalt"],
    correctAnswer: "flink",
    explanation: "Flink bedeutet: schnell und wendig.",
    vocabData: { emoji: "🐇", definition: "Flink heißt: sehr schnell und beweglich.", example: "Das Kaninchen ist flink." },
    xpReward: 5 },
  { id: "voc-schoen", category: "vocabulary", klasse: 1,
    prompt: "schön",
    options: ["hässlich", "prächtig", "dunkel", "leise"],
    correctAnswer: "prächtig",
    explanation: "Prächtig bedeutet: sehr schön und wundervoll.",
    vocabData: { emoji: "✨", definition: "Prächtig heißt: wunderschön und beeindruckend.", example: "Der Schmetterling ist prächtig." },
    xpReward: 5 },
  { id: "voc-muede", category: "vocabulary", klasse: 1,
    prompt: "müde",
    options: ["wach", "erschöpft", "hungrig", "froh"],
    correctAnswer: "erschöpft",
    explanation: "Erschöpft bedeutet: sehr, sehr müde.",
    vocabData: { emoji: "😴", definition: "Erschöpft heißt: total müde, keine Kraft mehr.", example: "Nach dem Laufen bin ich erschöpft." },
    xpReward: 5 },
  { id: "voc-nett", category: "vocabulary", klasse: 1,
    prompt: "nett",
    options: ["freundlich", "böse", "laut", "traurig"],
    correctAnswer: "freundlich",
    explanation: "Freundlich bedeutet: nett und hilfsbereit.",
    vocabData: { emoji: "😊", definition: "Freundlich heißt: nett zu anderen sein.", example: "Die Lehrerin ist sehr freundlich." },
    xpReward: 5 },
  { id: "voc-boese", category: "vocabulary", klasse: 1,
    prompt: "böse",
    options: ["wütend", "nett", "froh", "ruhig"],
    correctAnswer: "wütend",
    explanation: "Wütend bedeutet: sehr böse und ärgerlich.",
    vocabData: { emoji: "😠", definition: "Wütend heißt: sehr ärgerlich und aufgebracht.", example: "Er ist wütend, weil sein Spielzeug kaputt ist." },
    xpReward: 5 },
  { id: "voc-froh", category: "vocabulary", klasse: 1,
    prompt: "froh",
    options: ["traurig", "glücklich", "müde", "wütend"],
    correctAnswer: "glücklich",
    explanation: "Glücklich bedeutet: froh und zufrieden.",
    vocabData: { emoji: "😄", definition: "Glücklich heißt: sehr froh und zufrieden.", example: "Sie ist glücklich über ihr Geschenk." },
    xpReward: 5 },
  { id: "voc-kalt", category: "vocabulary", klasse: 1,
    prompt: "kalt",
    options: ["warm", "eisig", "heiß", "weich"],
    correctAnswer: "eisig",
    explanation: "Eisig bedeutet: sehr, sehr kalt – wie Eis!",
    vocabData: { emoji: "🧊", definition: "Eisig heißt: sehr kalt, wie Eis.", example: "Der Wind ist eisig kalt." },
    xpReward: 5 },
  { id: "voc-hell", category: "vocabulary", klasse: 1,
    prompt: "hell",
    options: ["dunkel", "strahlend", "grau", "finster"],
    correctAnswer: "strahlend",
    explanation: "Strahlend bedeutet: sehr hell und leuchtend.",
    vocabData: { emoji: "☀️", definition: "Strahlend heißt: sehr hell und leuchtend.", example: "Die Sonne scheint strahlend." },
    xpReward: 5 },
  { id: "voc-dunkel", category: "vocabulary", klasse: 1,
    prompt: "dunkel",
    options: ["hell", "finster", "bunt", "laut"],
    correctAnswer: "finster",
    explanation: "Finster bedeutet: sehr dunkel, kein Licht.",
    vocabData: { emoji: "🌑", definition: "Finster heißt: sehr dunkel, kein Licht da.", example: "In der Nacht ist es finster." },
    xpReward: 5 },
  { id: "voc-alt", category: "vocabulary", klasse: 1,
    prompt: "alt",
    options: ["jung", "uralt", "neu", "klein"],
    correctAnswer: "uralt",
    explanation: "Uralt bedeutet: sehr, sehr alt.",
    vocabData: { emoji: "🦕", definition: "Uralt heißt: schon sehr, sehr lange auf der Welt.", example: "Der Baum ist uralt." },
    xpReward: 5 },
  { id: "voc-neu", category: "vocabulary", klasse: 1,
    prompt: "neu",
    options: ["alt", "frisch", "kaputt", "müde"],
    correctAnswer: "frisch",
    explanation: "Frisch bedeutet: neu und sauber.",
    vocabData: { emoji: "🌱", definition: "Frisch heißt: neu, gerade erst da.", example: "Das Brot ist frisch gebacken." },
    xpReward: 5 },
  { id: "voc-klein", category: "vocabulary", klasse: 1,
    prompt: "klein",
    options: ["groß", "riesig", "winzig", "breit"],
    correctAnswer: "winzig",
    explanation: "Winzig bedeutet: sehr, sehr klein.",
    vocabData: { emoji: "🐜", definition: "Winzig heißt: unglaublich klein.", example: "Die Ameise ist winzig." },
    xpReward: 5 },
  { id: "voc-stark", category: "vocabulary", klasse: 1,
    prompt: "stark",
    options: ["schwach", "kräftig", "klein", "leise"],
    correctAnswer: "kräftig",
    explanation: "Kräftig bedeutet: stark und gesund.",
    vocabData: { emoji: "💪", definition: "Kräftig heißt: stark und voller Kraft.", example: "Der Bär ist sehr kräftig." },
    xpReward: 5 },
  { id: "voc-ruhig", category: "vocabulary", klasse: 1,
    prompt: "ruhig",
    options: ["laut", "still", "wild", "lustig"],
    correctAnswer: "still",
    explanation: "Still bedeutet: ruhig, kein Lärm.",
    vocabData: { emoji: "🤫", definition: "Still heißt: ruhig und ohne Lärm.", example: "Es ist ganz still im Wald." },
    xpReward: 5 },
  { id: "voc-lustig", category: "vocabulary", klasse: 1,
    prompt: "lustig",
    options: ["traurig", "langweilig", "witzig", "müde"],
    correctAnswer: "witzig",
    explanation: "Witzig bedeutet: lustig und zum Lachen.",
    vocabData: { emoji: "😂", definition: "Witzig heißt: so lustig, dass man lachen muss.", example: "Der Witz ist sehr witzig." },
    xpReward: 5 },
  { id: "voc-klug", category: "vocabulary", klasse: 1,
    prompt: "klug",
    options: ["dumm", "schlau", "langsam", "laut"],
    correctAnswer: "schlau",
    explanation: "Schlau bedeutet: klug und listig.",
    vocabData: { emoji: "🦊", definition: "Schlau heißt: klug und clever.", example: "Der Fuchs ist sehr schlau." },
    xpReward: 5 },
  { id: "voc-leer", category: "vocabulary", klasse: 1,
    prompt: "leer",
    options: ["voll", "leer", "offen", "hohl"],
    correctAnswer: "hohl",
    explanation: "Hohl bedeutet: leer innen drin.",
    vocabData: { emoji: "🫙", definition: "Hohl heißt: innen drin ist nichts.", example: "Der Baum ist innen hohl." },
    xpReward: 5 },
  { id: "voc-voll", category: "vocabulary", klasse: 1,
    prompt: "voll",
    options: ["leer", "gefüllt", "klein", "flach"],
    correctAnswer: "gefüllt",
    explanation: "Gefüllt bedeutet: so voll, dass nichts mehr rein passt.",
    vocabData: { emoji: "🎒", definition: "Gefüllt heißt: so voll wie möglich.", example: "Der Rucksack ist komplett gefüllt." },
    xpReward: 5 },
  { id: "voc-traurig", category: "vocabulary", klasse: 1,
    prompt: "traurig",
    options: ["froh", "betrübt", "glücklich", "lustig"],
    correctAnswer: "betrübt",
    explanation: "Betrübt bedeutet: traurig und unglücklich.",
    vocabData: { emoji: "😢", definition: "Betrübt heißt: sehr traurig und unglücklich.", example: "Das Kind ist betrübt, weil sein Ball weg ist." },
    xpReward: 5 },

  // ── Klasse 2 ────────────────────────────────────────────────────────────────
  { id: "voc-froehlich", category: "vocabulary", klasse: 2,
    prompt: "fröhlich",
    options: ["traurig", "heiter", "böse", "müde"],
    correctAnswer: "heiter",
    explanation: "Heiter bedeutet: gut gelaunt und fröhlich.",
    vocabData: { emoji: "🌤️", definition: "Heiter heißt: gut gelaunt und fröhlich.", example: "Sie ist heute heiter gestimmt." },
    xpReward: 5 },
  { id: "voc-seltsam", category: "vocabulary", klasse: 2,
    prompt: "seltsam",
    options: ["normal", "merkwürdig", "schön", "laut"],
    correctAnswer: "merkwürdig",
    explanation: "Merkwürdig bedeutet: seltsam und komisch.",
    vocabData: { emoji: "🤔", definition: "Merkwürdig heißt: seltsam und ungewöhnlich.", example: "Das Geräusch klingt merkwürdig." },
    xpReward: 5 },
  { id: "voc-lecker", category: "vocabulary", klasse: 2,
    prompt: "lecker",
    options: ["eklig", "köstlich", "sauer", "bitter"],
    correctAnswer: "köstlich",
    explanation: "Köstlich bedeutet: sehr lecker und wohlschmeckend.",
    vocabData: { emoji: "😋", definition: "Köstlich heißt: sehr lecker, schmeckt wunderbar.", example: "Die Torte ist köstlich." },
    xpReward: 5 },
  { id: "voc-fleissig", category: "vocabulary", klasse: 2,
    prompt: "fleißig",
    options: ["faul", "eifrig", "langsam", "müde"],
    correctAnswer: "eifrig",
    explanation: "Eifrig bedeutet: mit viel Eifer und Fleiß bei der Sache.",
    vocabData: { emoji: "📚", definition: "Eifrig heißt: sehr fleißig und engagiert.", example: "Sie lernt eifrig für die Schule." },
    xpReward: 5 },
  { id: "voc-faul", category: "vocabulary", klasse: 2,
    prompt: "faul",
    options: ["fleißig", "träge", "schnell", "nett"],
    correctAnswer: "träge",
    explanation: "Träge bedeutet: langsam und ohne Schwung.",
    vocabData: { emoji: "🦥", definition: "Träge heißt: langsam und ohne Energie.", example: "Das Faultier ist sehr träge." },
    xpReward: 5 },
  { id: "voc-sauber", category: "vocabulary", klasse: 2,
    prompt: "sauber",
    options: ["schmutzig", "rein", "nass", "alt"],
    correctAnswer: "rein",
    explanation: "Rein bedeutet: sauber, ohne Schmutz.",
    vocabData: { emoji: "✨", definition: "Rein heißt: ganz sauber, kein Schmutz dabei.", example: "Die Wäsche ist frisch und rein." },
    xpReward: 5 },
  { id: "voc-schmutzig", category: "vocabulary", klasse: 2,
    prompt: "schmutzig",
    options: ["sauber", "dreckig", "nass", "trocken"],
    correctAnswer: "dreckig",
    explanation: "Dreckig bedeutet: schmutzig, voller Schmutz.",
    vocabData: { emoji: "🪣", definition: "Dreckig heißt: sehr schmutzig.", example: "Die Hände sind dreckig nach dem Spielen." },
    xpReward: 5 },
  { id: "voc-einfach", category: "vocabulary", klasse: 2,
    prompt: "einfach",
    options: ["schwer", "leicht", "groß", "laut"],
    correctAnswer: "leicht",
    explanation: "Leicht bedeutet: einfach, ohne große Mühe.",
    vocabData: { emoji: "🎯", definition: "Leicht heißt: einfach zu schaffen.", example: "Die Aufgabe ist leicht." },
    xpReward: 5 },
  { id: "voc-schwer", category: "vocabulary", klasse: 2,
    prompt: "schwer",
    options: ["leicht", "schwierig", "klein", "schnell"],
    correctAnswer: "schwierig",
    explanation: "Schwierig bedeutet: nicht leicht, man muss sich anstrengen.",
    vocabData: { emoji: "🧩", definition: "Schwierig heißt: nicht leicht, erfordert Mühe.", example: "Das Rätsel ist schwierig." },
    xpReward: 5 },
  { id: "voc-aufgeregt", category: "vocabulary", klasse: 2,
    prompt: "aufgeregt",
    options: ["ruhig", "gespannt", "müde", "traurig"],
    correctAnswer: "gespannt",
    explanation: "Gespannt bedeutet: aufgeregt und voller Erwartung.",
    vocabData: { emoji: "🎉", definition: "Gespannt heißt: aufgeregt und voller Vorfreude.", example: "Er ist gespannt auf sein Geschenk." },
    xpReward: 5 },
  { id: "voc-gemuetlich", category: "vocabulary", klasse: 2,
    prompt: "gemütlich",
    options: ["unbequem", "behaglich", "kalt", "laut"],
    correctAnswer: "behaglich",
    explanation: "Behaglich bedeutet: gemütlich und wohl.",
    vocabData: { emoji: "🛋️", definition: "Behaglich heißt: gemütlich und angenehm.", example: "Das Sofa ist sehr behaglich." },
    xpReward: 5 },
  { id: "voc-hilfreich", category: "vocabulary", klasse: 2,
    prompt: "hilfreich",
    options: ["nutzlos", "nützlich", "langsam", "schwer"],
    correctAnswer: "nützlich",
    explanation: "Nützlich bedeutet: hilfreich und von Nutzen.",
    vocabData: { emoji: "🔧", definition: "Nützlich heißt: sehr hilfreich und praktisch.", example: "Ein Werkzeug ist sehr nützlich." },
    xpReward: 5 },
  { id: "voc-laut2", category: "vocabulary", klasse: 2,
    prompt: "laut",
    options: ["leise", "lärmend", "still", "ruhig"],
    correctAnswer: "lärmend",
    explanation: "Lärmend bedeutet: sehr laut und störend.",
    vocabData: { emoji: "📢", definition: "Lärmend heißt: sehr laut und störend.", example: "Die Baustelle ist lärmend." },
    xpReward: 5 },
  { id: "voc-leise", category: "vocabulary", klasse: 2,
    prompt: "leise",
    options: ["laut", "sanft", "wild", "stark"],
    correctAnswer: "sanft",
    explanation: "Sanft bedeutet: leise und zart.",
    vocabData: { emoji: "🌸", definition: "Sanft heißt: leise, zart und behutsam.", example: "Sie singt sanft." },
    xpReward: 5 },
  { id: "voc-schoen2", category: "vocabulary", klasse: 2,
    prompt: "wunderschön",
    options: ["hässlich", "herrlich", "grau", "langweilig"],
    correctAnswer: "herrlich",
    explanation: "Herrlich bedeutet: wunderschön und großartig.",
    vocabData: { emoji: "🌅", definition: "Herrlich heißt: wunderschön und beeindruckend.", example: "Der Sonnenuntergang ist herrlich." },
    xpReward: 5 },
  { id: "voc-spannend", category: "vocabulary", klasse: 2,
    prompt: "spannend",
    options: ["langweilig", "aufregend", "ruhig", "leise"],
    correctAnswer: "aufregend",
    explanation: "Aufregend bedeutet: spannend und interessant.",
    vocabData: { emoji: "🎢", definition: "Aufregend heißt: spannend und mitreißend.", example: "Der Film ist sehr aufregend." },
    xpReward: 5 },
  { id: "voc-ehrlich", category: "vocabulary", klasse: 2,
    prompt: "ehrlich",
    options: ["verlogen", "aufrichtig", "still", "faul"],
    correctAnswer: "aufrichtig",
    explanation: "Aufrichtig bedeutet: ehrlich und offen.",
    vocabData: { emoji: "🤝", definition: "Aufrichtig heißt: ehrlich und offen zu anderen.", example: "Sie ist immer aufrichtig." },
    xpReward: 5 },
  { id: "voc-langweilig", category: "vocabulary", klasse: 2,
    prompt: "langweilig",
    options: ["spannend", "öde", "lustig", "nett"],
    correctAnswer: "öde",
    explanation: "Öde bedeutet: langweilig, nichts Interessantes.",
    vocabData: { emoji: "😑", definition: "Öde heißt: sehr langweilig, nichts los.", example: "Das Wetter ist heute öde." },
    xpReward: 5 },
  { id: "voc-lustig2", category: "vocabulary", klasse: 2,
    prompt: "spaßig",
    options: ["traurig", "amüsant", "langweilig", "streng"],
    correctAnswer: "amüsant",
    explanation: "Amüsant bedeutet: lustig und unterhaltend.",
    vocabData: { emoji: "🎭", definition: "Amüsant heißt: lustig und unterhaltend.", example: "Das Theaterstück war sehr amüsant." },
    xpReward: 5 },
  { id: "voc-fremd", category: "vocabulary", klasse: 2,
    prompt: "fremd",
    options: ["bekannt", "unbekannt", "vertraut", "nett"],
    correctAnswer: "unbekannt",
    explanation: "Unbekannt bedeutet: fremd, man kennt es nicht.",
    vocabData: { emoji: "❓", definition: "Unbekannt heißt: fremdartig, noch nie gesehen.", example: "Das Tier ist mir unbekannt." },
    xpReward: 5 },

  // ── Klasse 3 ────────────────────────────────────────────────────────────────
  { id: "voc-tapfer", category: "vocabulary", klasse: 3,
    prompt: "tapfer",
    options: ["ängstlich", "mutig", "faul", "laut"],
    correctAnswer: "mutig",
    explanation: "Mutig bedeutet: tapfer, keine Angst haben.",
    vocabData: { emoji: "🦁", definition: "Mutig heißt: tapfer und ohne Angst.", example: "Der Feuerwehrmann ist sehr mutig." },
    xpReward: 5 },
  { id: "voc-neugierig", category: "vocabulary", klasse: 3,
    prompt: "neugierig",
    options: ["gleichgültig", "wissbegierig", "traurig", "müde"],
    correctAnswer: "wissbegierig",
    explanation: "Wissbegierig bedeutet: neugierig und lernwillig.",
    vocabData: { emoji: "🔍", definition: "Wissbegierig heißt: sehr neugierig und will alles wissen.", example: "Sie ist wissbegierig und liest viele Bücher." },
    xpReward: 5 },
  { id: "voc-schuechtern", category: "vocabulary", klasse: 3,
    prompt: "schüchtern",
    options: ["mutig", "zurückhaltend", "laut", "frech"],
    correctAnswer: "zurückhaltend",
    explanation: "Zurückhaltend bedeutet: schüchtern und vorsichtig.",
    vocabData: { emoji: "🌷", definition: "Zurückhaltend heißt: schüchtern und zurückgezogen.", example: "Das neue Kind ist noch zurückhaltend." },
    xpReward: 5 },
  { id: "voc-geduldig", category: "vocabulary", klasse: 3,
    prompt: "geduldig",
    options: ["ungeduldig", "ausdauernd", "schnell", "laut"],
    correctAnswer: "ausdauernd",
    explanation: "Ausdauernd bedeutet: geduldig und hartnäckig.",
    vocabData: { emoji: "🐢", definition: "Ausdauernd heißt: lange dabei bleiben und nicht aufgeben.", example: "Die Schildkröte ist ausdauernd." },
    xpReward: 5 },
  { id: "voc-sanft", category: "vocabulary", klasse: 3,
    prompt: "sanft",
    options: ["rau", "zart", "hart", "laut"],
    correctAnswer: "zart",
    explanation: "Zart bedeutet: sanft und behutsam.",
    vocabData: { emoji: "🌸", definition: "Zart heißt: sehr sanft und vorsichtig.", example: "Sie streichelt die Katze zart." },
    xpReward: 5 },
  { id: "voc-wuetend", category: "vocabulary", klasse: 3,
    prompt: "wütend",
    options: ["fröhlich", "zornig", "ruhig", "müde"],
    correctAnswer: "zornig",
    explanation: "Zornig bedeutet: sehr wütend und verärgert.",
    vocabData: { emoji: "😤", definition: "Zornig heißt: sehr wütend und aufgebracht.", example: "Er ist zornig über die Ungerechtigkeit." },
    xpReward: 5 },
  { id: "voc-erschoepft", category: "vocabulary", klasse: 3,
    prompt: "erschöpft",
    options: ["ausgeruht", "ausgelaugt", "frisch", "froh"],
    correctAnswer: "ausgelaugt",
    explanation: "Ausgelaugt bedeutet: komplett erschöpft, ohne Energie.",
    vocabData: { emoji: "🪫", definition: "Ausgelaugt heißt: total erschöpft, leer wie eine leere Batterie.", example: "Nach dem langen Wandern bin ich ausgelaugt." },
    xpReward: 5 },
  { id: "voc-klugerKopf", category: "vocabulary", klasse: 3,
    prompt: "klug",
    options: ["dumm", "intelligent", "langsam", "still"],
    correctAnswer: "intelligent",
    explanation: "Intelligent bedeutet: klug und geistig gewandt.",
    vocabData: { emoji: "🧠", definition: "Intelligent heißt: sehr klug und findig.", example: "Der Wissenschaftler ist sehr intelligent." },
    xpReward: 5 },
  { id: "voc-wunderschoen", category: "vocabulary", klasse: 3,
    prompt: "wunderschön",
    options: ["hässlich", "malerisch", "grau", "laut"],
    correctAnswer: "malerisch",
    explanation: "Malerisch bedeutet: so schön wie ein Gemälde.",
    vocabData: { emoji: "🎨", definition: "Malerisch heißt: wunderschön wie auf einem Gemälde.", example: "Das Dorf ist malerisch gelegen." },
    xpReward: 5 },
  { id: "voc-gefaehrlich", category: "vocabulary", klasse: 3,
    prompt: "gefährlich",
    options: ["sicher", "riskant", "langweilig", "nett"],
    correctAnswer: "riskant",
    explanation: "Riskant bedeutet: gefährlich, mit Risiko.",
    vocabData: { emoji: "⚠️", definition: "Riskant heißt: mit Risiko verbunden, gefährlich.", example: "Das Klettern ohne Sicherung ist riskant." },
    xpReward: 5 },
  { id: "voc-standhaft", category: "vocabulary", klasse: 3,
    prompt: "standhaft",
    options: ["schwach", "beharrlich", "ängstlich", "leise"],
    correctAnswer: "beharrlich",
    explanation: "Beharrlich bedeutet: standhaft und nicht aufgebend.",
    vocabData: { emoji: "🗿", definition: "Beharrlich heißt: nicht aufgeben, dran bleiben.", example: "Sie übt beharrlich weiter." },
    xpReward: 5 },
  { id: "voc-sonderbar", category: "vocabulary", klasse: 3,
    prompt: "sonderbar",
    options: ["normal", "eigenartig", "schön", "laut"],
    correctAnswer: "eigenartig",
    explanation: "Eigenartig bedeutet: sonderbar und ungewöhnlich.",
    vocabData: { emoji: "🤨", definition: "Eigenartig heißt: sonderbar und anders als sonst.", example: "Das Verhalten der Katze ist eigenartig." },
    xpReward: 5 },
  { id: "voc-heiter", category: "vocabulary", klasse: 3,
    prompt: "heiter",
    options: ["traurig", "vergnügt", "dunkel", "laut"],
    correctAnswer: "vergnügt",
    explanation: "Vergnügt bedeutet: fröhlich und gut gelaunt.",
    vocabData: { emoji: "😁", definition: "Vergnügt heißt: fröhlich und in bester Laune.", example: "Er lacht vergnügt." },
    xpReward: 5 },
  { id: "voc-ehrenhaft", category: "vocabulary", klasse: 3,
    prompt: "ehrenhaft",
    options: ["unehrlich", "anständig", "faul", "laut"],
    correctAnswer: "anständig",
    explanation: "Anständig bedeutet: ehrenhaft und respektvoll.",
    vocabData: { emoji: "🎖️", definition: "Anständig heißt: ehrenhaft und fair zu anderen.", example: "Er verhält sich anständig." },
    xpReward: 5 },
  { id: "voc-begeistert", category: "vocabulary", klasse: 3,
    prompt: "begeistert",
    options: ["gleichgültig", "enthusiastisch", "müde", "traurig"],
    correctAnswer: "enthusiastisch",
    explanation: "Enthusiastisch bedeutet: begeistert und voller Feuer.",
    vocabData: { emoji: "🔥", definition: "Enthusiastisch heißt: sehr begeistert und mitreißend.", example: "Sie singt enthusiastisch." },
    xpReward: 5 },
  { id: "voc-sparsam", category: "vocabulary", klasse: 3,
    prompt: "sparsam",
    options: ["verschwenderisch", "haushälterisch", "laut", "schnell"],
    correctAnswer: "haushälterisch",
    explanation: "Haushälterisch bedeutet: sparsam mit Dingen umgehen.",
    vocabData: { emoji: "💰", definition: "Haushälterisch heißt: sparsam und gut mit Ressourcen umgehen.", example: "Sie geht haushälterisch mit Wasser um." },
    xpReward: 5 },
  { id: "voc-prachtvoll", category: "vocabulary", klasse: 3,
    prompt: "prachtvoll",
    options: ["schlicht", "großartig", "klein", "leise"],
    correctAnswer: "großartig",
    explanation: "Großartig bedeutet: wundervoll und beeindruckend.",
    vocabData: { emoji: "🏰", definition: "Großartig heißt: sehr beeindruckend und wundervoll.", example: "Das Schloss ist großartig." },
    xpReward: 5 },
  { id: "voc-fuersorglich", category: "vocabulary", klasse: 3,
    prompt: "fürsorglich",
    options: ["gleichgültig", "aufmerksam", "laut", "schnell"],
    correctAnswer: "aufmerksam",
    explanation: "Aufmerksam bedeutet: fürsorglich und anderen gegenüber sensibel.",
    vocabData: { emoji: "🤗", definition: "Aufmerksam heißt: auf andere achten und fürsorglich sein.", example: "Sie ist sehr aufmerksam gegenüber ihren Freunden." },
    xpReward: 5 },
  { id: "voc-strahlend", category: "vocabulary", klasse: 3,
    prompt: "strahlend",
    options: ["dunkel", "leuchtend", "still", "kalt"],
    correctAnswer: "leuchtend",
    explanation: "Leuchtend bedeutet: sehr hell und strahlend.",
    vocabData: { emoji: "💡", definition: "Leuchtend heißt: hell und strahlend wie ein Licht.", example: "Die Blumen haben leuchtende Farben." },
    xpReward: 5 },
  { id: "voc-gerecht", category: "vocabulary", klasse: 3,
    prompt: "gerecht",
    options: ["unfair", "fair", "streng", "laut"],
    correctAnswer: "fair",
    explanation: "Fair bedeutet: gerecht und ehrlich zu allen.",
    vocabData: { emoji: "⚖️", definition: "Fair heißt: gerecht und alle gleich behandeln.", example: "Der Lehrer ist fair zu allen Schülern." },
    xpReward: 5 },

  // ── Klasse 4 ────────────────────────────────────────────────────────────────
  { id: "voc-aussergewoehnlich", category: "vocabulary", klasse: 4,
    prompt: "außergewöhnlich",
    options: ["normal", "gewöhnlich", "ungewöhnlich", "langweilig"],
    correctAnswer: "ungewöhnlich",
    explanation: "Ungewöhnlich bedeutet: nicht normal, außergewöhnlich.",
    vocabData: { emoji: "🌟", definition: "Ungewöhnlich heißt: besonders und nicht alltäglich.", example: "Er hat eine ungewöhnliche Begabung." },
    xpReward: 5 },
  { id: "voc-hartnaeckig", category: "vocabulary", klasse: 4,
    prompt: "hartnäckig",
    options: ["nachgiebig", "beharrlich", "faul", "schnell"],
    correctAnswer: "beharrlich",
    explanation: "Beharrlich bedeutet: hartnäckig und nicht aufgebend.",
    vocabData: { emoji: "💪", definition: "Beharrlich heißt: nicht aufgeben, trotz Hindernissen weitermachen.", example: "Sie arbeitet beharrlich an ihrer Erfindung." },
    xpReward: 5 },
  { id: "voc-erstaunlich", category: "vocabulary", klasse: 4,
    prompt: "erstaunlich",
    options: ["langweilig", "verblüffend", "normal", "klein"],
    correctAnswer: "verblüffend",
    explanation: "Verblüffend bedeutet: erstaunlich und überraschend.",
    vocabData: { emoji: "😲", definition: "Verblüffend heißt: so überraschend, dass man staunt.", example: "Das Kunststück ist verblüffend." },
    xpReward: 5 },
  { id: "voc-gefasst", category: "vocabulary", klasse: 4,
    prompt: "gefasst",
    options: ["aufgeregt", "besonnen", "laut", "wild"],
    correctAnswer: "besonnen",
    explanation: "Besonnen bedeutet: ruhig und gefasst in schwierigen Situationen.",
    vocabData: { emoji: "🧘", definition: "Besonnen heißt: ruhig und überlegt handeln.", example: "Sie reagiert besonnen in der Krise." },
    xpReward: 5 },
  { id: "voc-praezise", category: "vocabulary", klasse: 4,
    prompt: "präzise",
    options: ["ungenau", "exakt", "laut", "schnell"],
    correctAnswer: "exakt",
    explanation: "Exakt bedeutet: präzise und ohne Fehler.",
    vocabData: { emoji: "🎯", definition: "Exakt heißt: sehr genau und ohne den kleinsten Fehler.", example: "Die Messung ist exakt." },
    xpReward: 5 },
  { id: "voc-unerschrocken", category: "vocabulary", klasse: 4,
    prompt: "unerschrocken",
    options: ["ängstlich", "furchtlos", "ruhig", "langsam"],
    correctAnswer: "furchtlos",
    explanation: "Furchtlos bedeutet: ohne jede Angst, mutig.",
    vocabData: { emoji: "🦸", definition: "Furchtlos heißt: ohne Angst, sehr mutig.", example: "Der Held ist furchtlos." },
    xpReward: 5 },
  { id: "voc-verzweifelt", category: "vocabulary", klasse: 4,
    prompt: "verzweifelt",
    options: ["hoffnungsvoll", "hoffnungslos", "fröhlich", "ruhig"],
    correctAnswer: "hoffnungslos",
    explanation: "Hoffnungslos bedeutet: ohne Hoffnung, verzweifelt.",
    vocabData: { emoji: "😞", definition: "Hoffnungslos heißt: ohne Hoffnung auf eine Lösung.", example: "Die Situation schien hoffnungslos." },
    xpReward: 5 },
  { id: "voc-bescheiden", category: "vocabulary", klasse: 4,
    prompt: "bescheiden",
    options: ["arrogant", "demütig", "laut", "schnell"],
    correctAnswer: "demütig",
    explanation: "Demütig bedeutet: bescheiden und nicht überheblich.",
    vocabData: { emoji: "🙏", definition: "Demütig heißt: bescheiden und nicht prahlend.", example: "Er nimmt den Preis demütig entgegen." },
    xpReward: 5 },
  { id: "voc-bemerkenswert", category: "vocabulary", klasse: 4,
    prompt: "bemerkenswert",
    options: ["unbeachtet", "auffallend", "gewöhnlich", "still"],
    correctAnswer: "auffallend",
    explanation: "Auffallend bedeutet: so besonders, dass man es bemerkt.",
    vocabData: { emoji: "👀", definition: "Auffallend heißt: so besonders, dass es sofort auffällt.", example: "Sie hat ein auffallend gutes Gedächtnis." },
    xpReward: 5 },
  { id: "voc-vertrauenswuerdig", category: "vocabulary", klasse: 4,
    prompt: "vertrauenswürdig",
    options: ["unzuverlässig", "zuverlässig", "langsam", "laut"],
    correctAnswer: "zuverlässig",
    explanation: "Zuverlässig bedeutet: man kann sich darauf verlassen.",
    vocabData: { emoji: "🔒", definition: "Zuverlässig heißt: immer verlässlich und vertrauenswürdig.", example: "Sie ist eine zuverlässige Freundin." },
    xpReward: 5 },
  { id: "voc-wohlhabend", category: "vocabulary", klasse: 4,
    prompt: "wohlhabend",
    options: ["arm", "begütert", "fleißig", "krank"],
    correctAnswer: "begütert",
    explanation: "Begütert bedeutet: reich und wohlhabend.",
    vocabData: { emoji: "💎", definition: "Begütert heißt: wohlhabend, hat viel Geld oder Besitz.", example: "Die Familie ist begütert." },
    xpReward: 5 },
  { id: "voc-ungeduldig", category: "vocabulary", klasse: 4,
    prompt: "ungeduldig",
    options: ["geduldig", "hastig", "ruhig", "langsam"],
    correctAnswer: "hastig",
    explanation: "Hastig bedeutet: ungeduldig und übereilt.",
    vocabData: { emoji: "⏰", definition: "Hastig heißt: schnell und unruhig, ohne Geduld.", example: "Er isst hastig, weil er es eilig hat." },
    xpReward: 5 },
  { id: "voc-bedeutsam", category: "vocabulary", klasse: 4,
    prompt: "bedeutsam",
    options: ["unwichtig", "wesentlich", "klein", "leise"],
    correctAnswer: "wesentlich",
    explanation: "Wesentlich bedeutet: wichtig und bedeutsam.",
    vocabData: { emoji: "💡", definition: "Wesentlich heißt: sehr wichtig und bedeutsam.", example: "Das ist ein wesentlicher Unterschied." },
    xpReward: 5 },
  { id: "voc-unabhaengig", category: "vocabulary", klasse: 4,
    prompt: "unabhängig",
    options: ["abhängig", "eigenständig", "schwach", "laut"],
    correctAnswer: "eigenständig",
    explanation: "Eigenständig bedeutet: unabhängig und selbstständig.",
    vocabData: { emoji: "🦅", definition: "Eigenständig heißt: alleine und ohne Hilfe auskommen.", example: "Sie löst die Aufgabe eigenständig." },
    xpReward: 5 },
  { id: "voc-furchterregend", category: "vocabulary", klasse: 4,
    prompt: "furchterregend",
    options: ["niedlich", "erschreckend", "schön", "leise"],
    correctAnswer: "erschreckend",
    explanation: "Erschreckend bedeutet: angsteinflößend und furchterregend.",
    vocabData: { emoji: "👻", definition: "Erschreckend heißt: so beängstigend, dass man erschrickt.", example: "Der Donner war erschreckend laut." },
    xpReward: 5 },
  { id: "voc-aufmerksam", category: "vocabulary", klasse: 4,
    prompt: "aufmerksam",
    options: ["unaufmerksam", "konzentriert", "laut", "faul"],
    correctAnswer: "konzentriert",
    explanation: "Konzentriert bedeutet: aufmerksam und fokussiert.",
    vocabData: { emoji: "🎯", definition: "Konzentriert heißt: sehr aufmerksam und fokussiert.", example: "Sie arbeitet konzentriert." },
    xpReward: 5 },
  { id: "voc-grosszuegig", category: "vocabulary", klasse: 4,
    prompt: "großzügig",
    options: ["geizig", "freigiebig", "streng", "laut"],
    correctAnswer: "freigiebig",
    explanation: "Freigiebig bedeutet: großzügig und gerne gebend.",
    vocabData: { emoji: "🎁", definition: "Freigiebig heißt: großzügig und gerne etwas verschenken.", example: "Er ist sehr freigiebig mit seinen Spielsachen." },
    xpReward: 5 },
  { id: "voc-ratlos", category: "vocabulary", klasse: 4,
    prompt: "ratlos",
    options: ["entschlossen", "perplex", "ruhig", "stark"],
    correctAnswer: "perplex",
    explanation: "Perplex bedeutet: völlig ratlos und verblüfft.",
    vocabData: { emoji: "🤯", definition: "Perplex heißt: so überrascht, dass man nicht weiß, was man sagen soll.", example: "Er war perplex über die Nachricht." },
    xpReward: 5 },
  { id: "voc-beharrlich", category: "vocabulary", klasse: 4,
    prompt: "beharrlich",
    options: ["aufgebend", "stur", "schnell", "leise"],
    correctAnswer: "stur",
    explanation: "Stur bedeutet: sehr beharrlich, nicht nachgebend.",
    vocabData: { emoji: "🐂", definition: "Stur heißt: beharrlich und nicht bereit, nachzugeben.", example: "Er hält stur an seiner Meinung fest." },
    xpReward: 5 },
  { id: "voc-eigenartig", category: "vocabulary", klasse: 4,
    prompt: "eigenartig",
    options: ["normal", "skurril", "schön", "laut"],
    correctAnswer: "skurril",
    explanation: "Skurril bedeutet: seltsam und eigenartig.",
    vocabData: { emoji: "🎪", definition: "Skurril heißt: sehr seltsam und komisch.", example: "Das ist eine skurrile Geschichte." },
    xpReward: 5 },
];
