import type { GrammarExercise } from "../types/index.js";

// ─── Verb Conjugation (22 exercises, Klasse 1–3) ─────────────────────────────

export const verbConjugationExercises: GrammarExercise[] = [
  // spielen
  { id: "vc-spielen-ich", category: "verb-conjugation", klasse: 1,
    prompt: "Ich ___ Fußball. (spielen)",
    options: ["spiele", "spielst", "spielt", "spielen"],
    correctAnswer: "spiele",
    explanation: "Bei 'ich' hängt man -e an: spiel-e", xpReward: 5 },
  { id: "vc-spielen-du", category: "verb-conjugation", klasse: 1,
    prompt: "Du ___ gern Fußball. (spielen)",
    options: ["spiele", "spielst", "spielt", "spielen"],
    correctAnswer: "spielst",
    explanation: "Bei 'du' hängt man -st an: spiel-st", xpReward: 5 },
  { id: "vc-spielen-er", category: "verb-conjugation", klasse: 2,
    prompt: "Er ___ täglich im Garten. (spielen)",
    options: ["spiele", "spielst", "spielt", "spielen"],
    correctAnswer: "spielt",
    explanation: "Bei 'er/sie/es' hängt man -t an: spiel-t", xpReward: 5 },

  // laufen
  { id: "vc-laufen-ich", category: "verb-conjugation", klasse: 1,
    prompt: "Ich ___ sehr schnell. (laufen)",
    options: ["laufe", "läufst", "läuft", "laufen"],
    correctAnswer: "laufe",
    explanation: "Bei 'ich' bleibt der Stammvokal: lauf-e", xpReward: 5 },
  { id: "vc-laufen-du", category: "verb-conjugation", klasse: 2,
    prompt: "Du ___ jeden Morgen. (laufen)",
    options: ["laufe", "läufst", "läuft", "laufen"],
    correctAnswer: "läufst",
    explanation: "Bei 'du' ändert sich au→äu: läuf-st", xpReward: 5 },

  // essen
  { id: "vc-essen-ich", category: "verb-conjugation", klasse: 2,
    prompt: "Ich ___ gern Pizza. (essen)",
    options: ["esse", "isst", "esst", "essen"],
    correctAnswer: "esse",
    explanation: "Bei 'ich': ess-e", xpReward: 5 },
  { id: "vc-essen-du", category: "verb-conjugation", klasse: 2,
    prompt: "Du ___ dein Brot. (essen)",
    options: ["esse", "isst", "esst", "essen"],
    correctAnswer: "isst",
    explanation: "Bei 'du' ändert sich e→i: iss-t", xpReward: 5 },

  // trinken
  { id: "vc-trinken-ich", category: "verb-conjugation", klasse: 1,
    prompt: "Ich ___ Wasser. (trinken)",
    options: ["trinke", "trinkst", "trinkt", "trinken"],
    correctAnswer: "trinke",
    explanation: "Bei 'ich': trink-e", xpReward: 5 },
  { id: "vc-trinken-wir", category: "verb-conjugation", klasse: 2,
    prompt: "Wir ___ Saft zusammen. (trinken)",
    options: ["trinke", "trinkst", "trinkt", "trinken"],
    correctAnswer: "trinken",
    explanation: "Bei 'wir': trink-en", xpReward: 5 },

  // schreiben
  { id: "vc-schreiben-ich", category: "verb-conjugation", klasse: 2,
    prompt: "Ich ___ einen Brief. (schreiben)",
    options: ["schreibe", "schreibst", "schreibt", "schreiben"],
    correctAnswer: "schreibe",
    explanation: "Bei 'ich': schreib-e", xpReward: 5 },
  { id: "vc-schreiben-du", category: "verb-conjugation", klasse: 2,
    prompt: "Du ___ einen Aufsatz. (schreiben)",
    options: ["schreibe", "schreibst", "schreibt", "schreiben"],
    correctAnswer: "schreibst",
    explanation: "Bei 'du': schreib-st", xpReward: 5 },

  // lesen
  { id: "vc-lesen-du", category: "verb-conjugation", klasse: 2,
    prompt: "Du ___ ein Buch. (lesen)",
    options: ["lese", "liest", "lest", "lesen"],
    correctAnswer: "liest",
    explanation: "Bei 'du' ändert sich e→ie: lies-t", xpReward: 5 },
  { id: "vc-lesen-er", category: "verb-conjugation", klasse: 3,
    prompt: "Er ___ die Zeitung. (lesen)",
    options: ["lese", "liest", "lest", "lesen"],
    correctAnswer: "liest",
    explanation: "Bei 'er/sie/es' ändert sich e→ie: lies-t", xpReward: 5 },

  // machen
  { id: "vc-machen-er", category: "verb-conjugation", klasse: 1,
    prompt: "Er ___ seine Aufgaben. (machen)",
    options: ["mache", "machst", "macht", "machen"],
    correctAnswer: "macht",
    explanation: "Bei 'er/sie/es': mach-t", xpReward: 5 },
  { id: "vc-machen-wir", category: "verb-conjugation", klasse: 2,
    prompt: "Wir ___ einen Ausflug. (machen)",
    options: ["mache", "machst", "macht", "machen"],
    correctAnswer: "machen",
    explanation: "Bei 'wir': mach-en", xpReward: 5 },

  // haben
  { id: "vc-haben-ich", category: "verb-conjugation", klasse: 2,
    prompt: "Ich ___ Hunger. (haben)",
    options: ["habe", "hast", "hat", "haben"],
    correctAnswer: "habe",
    explanation: "Bei 'ich': hab-e", xpReward: 5 },
  { id: "vc-haben-er", category: "verb-conjugation", klasse: 2,
    prompt: "Er ___ einen Hund. (haben)",
    options: ["habe", "hast", "hat", "haben"],
    correctAnswer: "hat",
    explanation: "Bei 'er/sie/es': hat (unregelmäßig)", xpReward: 5 },

  // sein
  { id: "vc-sein-ich", category: "verb-conjugation", klasse: 2,
    prompt: "Ich ___ müde. (sein)",
    options: ["bin", "bist", "ist", "sind"],
    correctAnswer: "bin",
    explanation: "Bei 'ich': bin (sehr unregelmäßig)", xpReward: 5 },
  { id: "vc-sein-du", category: "verb-conjugation", klasse: 3,
    prompt: "Du ___ sehr nett. (sein)",
    options: ["bin", "bist", "ist", "sind"],
    correctAnswer: "bist",
    explanation: "Bei 'du': bist (sehr unregelmäßig)", xpReward: 5 },
  { id: "vc-sein-wir", category: "verb-conjugation", klasse: 3,
    prompt: "Wir ___ gute Freunde. (sein)",
    options: ["bin", "bist", "ist", "sind"],
    correctAnswer: "sind",
    explanation: "Bei 'wir': sind (sehr unregelmäßig)", xpReward: 5 },

  // gehen
  { id: "vc-gehen-ich", category: "verb-conjugation", klasse: 1,
    prompt: "Ich ___ zur Schule. (gehen)",
    options: ["gehe", "gehst", "geht", "gehen"],
    correctAnswer: "gehe",
    explanation: "Bei 'ich': geh-e", xpReward: 5 },
  { id: "vc-gehen-du", category: "verb-conjugation", klasse: 2,
    prompt: "Du ___ nach Hause. (gehen)",
    options: ["gehe", "gehst", "geht", "gehen"],
    correctAnswer: "gehst",
    explanation: "Bei 'du': geh-st", xpReward: 5 },
];

// ─── Noun Gender (31 nouns with emoji, Klasse 1–4) ───────────────────────────

export const nounGenderExercises: GrammarExercise[] = [
  // Klasse 1
  { id: "ng-hund", category: "noun-gender", klasse: 1,
    prompt: "🐕 Hund", options: ["der", "die", "das"], correctAnswer: "der",
    explanation: "Es heißt 'der Hund'", xpReward: 5 },
  { id: "ng-katze", category: "noun-gender", klasse: 1,
    prompt: "🐈 Katze", options: ["der", "die", "das"], correctAnswer: "die",
    explanation: "Es heißt 'die Katze'", xpReward: 5 },
  { id: "ng-haus", category: "noun-gender", klasse: 1,
    prompt: "🏠 Haus", options: ["der", "die", "das"], correctAnswer: "das",
    explanation: "Es heißt 'das Haus'", xpReward: 5 },
  { id: "ng-baum", category: "noun-gender", klasse: 1,
    prompt: "🌳 Baum", options: ["der", "die", "das"], correctAnswer: "der",
    explanation: "Es heißt 'der Baum'", xpReward: 5 },
  { id: "ng-blume", category: "noun-gender", klasse: 1,
    prompt: "🌸 Blume", options: ["der", "die", "das"], correctAnswer: "die",
    explanation: "Es heißt 'die Blume'", xpReward: 5 },
  { id: "ng-kind", category: "noun-gender", klasse: 1,
    prompt: "👶 Kind", options: ["der", "die", "das"], correctAnswer: "das",
    explanation: "Es heißt 'das Kind'", xpReward: 5 },
  { id: "ng-apfel", category: "noun-gender", klasse: 1,
    prompt: "🍎 Apfel", options: ["der", "die", "das"], correctAnswer: "der",
    explanation: "Es heißt 'der Apfel'", xpReward: 5 },
  { id: "ng-sonne", category: "noun-gender", klasse: 1,
    prompt: "☀️ Sonne", options: ["der", "die", "das"], correctAnswer: "die",
    explanation: "Es heißt 'die Sonne'", xpReward: 5 },
  { id: "ng-heft", category: "noun-gender", klasse: 1,
    prompt: "📓 Heft", options: ["der", "die", "das"], correctAnswer: "das",
    explanation: "Es heißt 'das Heft'", xpReward: 5 },
  { id: "ng-ball", category: "noun-gender", klasse: 1,
    prompt: "⚽ Ball", options: ["der", "die", "das"], correctAnswer: "der",
    explanation: "Es heißt 'der Ball'", xpReward: 5 },
  { id: "ng-pferd", category: "noun-gender", klasse: 1,
    prompt: "🐴 Pferd", options: ["der", "die", "das"], correctAnswer: "das",
    explanation: "Es heißt 'das Pferd'", xpReward: 5 },
  { id: "ng-schule", category: "noun-gender", klasse: 1,
    prompt: "🏫 Schule", options: ["der", "die", "das"], correctAnswer: "die",
    explanation: "Es heißt 'die Schule'", xpReward: 5 },
  // Klasse 2
  { id: "ng-tisch", category: "noun-gender", klasse: 2,
    prompt: "🪑 Tisch", options: ["der", "die", "das"], correctAnswer: "der",
    explanation: "Es heißt 'der Tisch'", xpReward: 5 },
  { id: "ng-auto", category: "noun-gender", klasse: 2,
    prompt: "🚗 Auto", options: ["der", "die", "das"], correctAnswer: "das",
    explanation: "Es heißt 'das Auto'", xpReward: 5 },
  { id: "ng-vogel", category: "noun-gender", klasse: 2,
    prompt: "🐦 Vogel", options: ["der", "die", "das"], correctAnswer: "der",
    explanation: "Es heißt 'der Vogel'", xpReward: 5 },
  { id: "ng-fisch", category: "noun-gender", klasse: 2,
    prompt: "🐟 Fisch", options: ["der", "die", "das"], correctAnswer: "der",
    explanation: "Es heißt 'der Fisch'", xpReward: 5 },
  { id: "ng-fenster", category: "noun-gender", klasse: 2,
    prompt: "🪟 Fenster", options: ["der", "die", "das"], correctAnswer: "das",
    explanation: "Es heißt 'das Fenster'", xpReward: 5 },
  { id: "ng-strasse", category: "noun-gender", klasse: 2,
    prompt: "🛣️ Straße", options: ["der", "die", "das"], correctAnswer: "die",
    explanation: "Es heißt 'die Straße'", xpReward: 5 },
  { id: "ng-fahrrad", category: "noun-gender", klasse: 2,
    prompt: "🚲 Fahrrad", options: ["der", "die", "das"], correctAnswer: "das",
    explanation: "Es heißt 'das Fahrrad'", xpReward: 5 },
  { id: "ng-buch", category: "noun-gender", klasse: 2,
    prompt: "📚 Buch", options: ["der", "die", "das"], correctAnswer: "das",
    explanation: "Es heißt 'das Buch'", xpReward: 5 },
  { id: "ng-bleistift", category: "noun-gender", klasse: 2,
    prompt: "✏️ Bleistift", options: ["der", "die", "das"], correctAnswer: "der",
    explanation: "Es heißt 'der Bleistift'", xpReward: 5 },
  { id: "ng-madchen", category: "noun-gender", klasse: 2,
    prompt: "👧 Mädchen", options: ["der", "die", "das"], correctAnswer: "das",
    explanation: "Alle Wörter mit -chen sind 'das': das Mädchen", xpReward: 5 },
  // Klasse 3
  { id: "ng-berg", category: "noun-gender", klasse: 3,
    prompt: "⛰️ Berg", options: ["der", "die", "das"], correctAnswer: "der",
    explanation: "Es heißt 'der Berg'", xpReward: 5 },
  { id: "ng-fluss", category: "noun-gender", klasse: 3,
    prompt: "🌊 Fluss", options: ["der", "die", "das"], correctAnswer: "der",
    explanation: "Es heißt 'der Fluss'", xpReward: 5 },
  { id: "ng-stadt", category: "noun-gender", klasse: 3,
    prompt: "🏙️ Stadt", options: ["der", "die", "das"], correctAnswer: "die",
    explanation: "Es heißt 'die Stadt'", xpReward: 5 },
  { id: "ng-wald", category: "noun-gender", klasse: 3,
    prompt: "🌲 Wald", options: ["der", "die", "das"], correctAnswer: "der",
    explanation: "Es heißt 'der Wald'", xpReward: 5 },
  { id: "ng-meer", category: "noun-gender", klasse: 3,
    prompt: "🌊 Meer", options: ["der", "die", "das"], correctAnswer: "das",
    explanation: "Es heißt 'das Meer'", xpReward: 5 },
  { id: "ng-brot", category: "noun-gender", klasse: 3,
    prompt: "🍞 Brot", options: ["der", "die", "das"], correctAnswer: "das",
    explanation: "Es heißt 'das Brot'", xpReward: 5 },
  // Klasse 4
  { id: "ng-zeitung", category: "noun-gender", klasse: 4,
    prompt: "📰 Zeitung", options: ["der", "die", "das"], correctAnswer: "die",
    explanation: "Es heißt 'die Zeitung'", xpReward: 5 },
  { id: "ng-telefon", category: "noun-gender", klasse: 4,
    prompt: "📱 Telefon", options: ["der", "die", "das"], correctAnswer: "das",
    explanation: "Es heißt 'das Telefon'", xpReward: 5 },
  { id: "ng-computer", category: "noun-gender", klasse: 4,
    prompt: "💻 Computer", options: ["der", "die", "das"], correctAnswer: "der",
    explanation: "Es heißt 'der Computer'", xpReward: 5 },
];

// ─── Singular & Plural (22 exercises, Klasse 1–4) ────────────────────────────

export const pluralExercises: GrammarExercise[] = [
  // Klasse 1
  { id: "pl-hund", category: "plural", klasse: 1,
    prompt: "Was ist die Mehrzahl von 'Hund'?",
    options: ["Hunde", "Hünde", "Hunden", "Hunds"],
    correctAnswer: "Hunde",
    explanation: "Die Mehrzahl von Hund ist Hunde", xpReward: 5 },
  { id: "pl-katze", category: "plural", klasse: 1,
    prompt: "Was ist die Mehrzahl von 'Katze'?",
    options: ["Katzen", "Kätze", "Katzens", "Katzes"],
    correctAnswer: "Katzen",
    explanation: "Die Mehrzahl von Katze ist Katzen", xpReward: 5 },
  { id: "pl-baum", category: "plural", klasse: 1,
    prompt: "Was ist die Mehrzahl von 'Baum'?",
    options: ["Bäume", "Baums", "Baume", "Bäum"],
    correctAnswer: "Bäume",
    explanation: "Die Mehrzahl von Baum ist Bäume (Umlaut + e)", xpReward: 5 },
  { id: "pl-haus", category: "plural", klasse: 1,
    prompt: "Was ist die Mehrzahl von 'Haus'?",
    options: ["Häuser", "Haus", "Häuse", "Hauser"],
    correctAnswer: "Häuser",
    explanation: "Die Mehrzahl von Haus ist Häuser (Umlaut + er)", xpReward: 5 },
  { id: "pl-kind", category: "plural", klasse: 1,
    prompt: "Was ist die Mehrzahl von 'Kind'?",
    options: ["Kinder", "Kinde", "Kindern", "Kinds"],
    correctAnswer: "Kinder",
    explanation: "Die Mehrzahl von Kind ist Kinder", xpReward: 5 },
  { id: "pl-blume", category: "plural", klasse: 1,
    prompt: "Was ist die Mehrzahl von 'Blume'?",
    options: ["Blumen", "Blümen", "Blumes", "Blume"],
    correctAnswer: "Blumen",
    explanation: "Die Mehrzahl von Blume ist Blumen", xpReward: 5 },
  // Klasse 2
  { id: "pl-buch", category: "plural", klasse: 2,
    prompt: "Was ist die Mehrzahl von 'Buch'?",
    options: ["Bücher", "Buchs", "Buchen", "Büch"],
    correctAnswer: "Bücher",
    explanation: "Die Mehrzahl von Buch ist Bücher (Umlaut + er)", xpReward: 5 },
  { id: "pl-tisch", category: "plural", klasse: 2,
    prompt: "Was ist die Mehrzahl von 'Tisch'?",
    options: ["Tische", "Tischen", "Tischs", "Täsche"],
    correctAnswer: "Tische",
    explanation: "Die Mehrzahl von Tisch ist Tische", xpReward: 5 },
  { id: "pl-ball", category: "plural", klasse: 2,
    prompt: "Was ist die Mehrzahl von 'Ball'?",
    options: ["Bälle", "Balls", "Balle", "Bällen"],
    correctAnswer: "Bälle",
    explanation: "Die Mehrzahl von Ball ist Bälle (Umlaut + e)", xpReward: 5 },
  { id: "pl-auto", category: "plural", klasse: 2,
    prompt: "Was ist die Mehrzahl von 'Auto'?",
    options: ["Autos", "Autoen", "Aute", "Äutos"],
    correctAnswer: "Autos",
    explanation: "Die Mehrzahl von Auto ist Autos (Fremdwort: + s)", xpReward: 5 },
  { id: "pl-vogel", category: "plural", klasse: 2,
    prompt: "Was ist die Mehrzahl von 'Vogel'?",
    options: ["Vögel", "Vogels", "Vogeln", "Vogele"],
    correctAnswer: "Vögel",
    explanation: "Die Mehrzahl von Vogel ist Vögel (Umlaut)", xpReward: 5 },
  { id: "pl-apfel", category: "plural", klasse: 2,
    prompt: "Was ist die Mehrzahl von 'Apfel'?",
    options: ["Äpfel", "Äpfels", "Apfeln", "Apfele"],
    correctAnswer: "Äpfel",
    explanation: "Die Mehrzahl von Apfel ist Äpfel (Umlaut)", xpReward: 5 },
  { id: "pl-stuhl", category: "plural", klasse: 2,
    prompt: "Was ist die Mehrzahl von 'Stuhl'?",
    options: ["Stühle", "Stuhls", "Stuhlen", "Stühlen"],
    correctAnswer: "Stühle",
    explanation: "Die Mehrzahl von Stuhl ist Stühle (Umlaut + e)", xpReward: 5 },
  { id: "pl-heft", category: "plural", klasse: 2,
    prompt: "Was ist die Mehrzahl von 'Heft'?",
    options: ["Hefte", "Heften", "Heftse", "Heft"],
    correctAnswer: "Hefte",
    explanation: "Die Mehrzahl von Heft ist Hefte", xpReward: 5 },
  // Klasse 3
  { id: "pl-berg", category: "plural", klasse: 3,
    prompt: "Was ist die Mehrzahl von 'Berg'?",
    options: ["Berge", "Bärge", "Bergs", "Bergen"],
    correctAnswer: "Berge",
    explanation: "Die Mehrzahl von Berg ist Berge", xpReward: 5 },
  { id: "pl-freund", category: "plural", klasse: 3,
    prompt: "Was ist die Mehrzahl von 'Freund'?",
    options: ["Freunde", "Freunden", "Freunds", "Freunde"],
    correctAnswer: "Freunde",
    explanation: "Die Mehrzahl von Freund ist Freunde", xpReward: 5 },
  { id: "pl-stadt", category: "plural", klasse: 3,
    prompt: "Was ist die Mehrzahl von 'Stadt'?",
    options: ["Städte", "Stätte", "Stadte", "Stadts"],
    correctAnswer: "Städte",
    explanation: "Die Mehrzahl von Stadt ist Städte (Umlaut + e)", xpReward: 5 },
  { id: "pl-strasse", category: "plural", klasse: 3,
    prompt: "Was ist die Mehrzahl von 'Straße'?",
    options: ["Straßen", "Straßes", "Straszen", "Straße"],
    correctAnswer: "Straßen",
    explanation: "Die Mehrzahl von Straße ist Straßen", xpReward: 5 },
  { id: "pl-lehrer", category: "plural", klasse: 3,
    prompt: "Was ist die Mehrzahl von 'Lehrer'?",
    options: ["Lehrer", "Lehrers", "Lehrern", "Lehre"],
    correctAnswer: "Lehrer",
    explanation: "Die Mehrzahl von Lehrer ist Lehrer (keine Änderung)", xpReward: 5 },
  { id: "pl-fenster", category: "plural", klasse: 3,
    prompt: "Was ist die Mehrzahl von 'Fenster'?",
    options: ["Fenster", "Fenstern", "Fenstere", "Fensters"],
    correctAnswer: "Fenster",
    explanation: "Die Mehrzahl von Fenster ist Fenster (keine Änderung)", xpReward: 5 },
  // Klasse 4
  { id: "pl-zeitung", category: "plural", klasse: 4,
    prompt: "Was ist die Mehrzahl von 'Zeitung'?",
    options: ["Zeitungen", "Zeitungs", "Zeitung", "Zeitünge"],
    correctAnswer: "Zeitungen",
    explanation: "Die Mehrzahl von Zeitung ist Zeitungen", xpReward: 5 },
  { id: "pl-erfindung", category: "plural", klasse: 4,
    prompt: "Was ist die Mehrzahl von 'Erfindung'?",
    options: ["Erfindungen", "Erfindungs", "Erfindunge", "Erfindüngen"],
    correctAnswer: "Erfindungen",
    explanation: "Wörter auf -ung bilden die Mehrzahl mit -en", xpReward: 5 },
];
